### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#1]
I noticed that the bibliography is not specfied, resulting in a compilation error.  This should be an easy fix by specifying all.bib and a bibliography style. I may have a style file I created a long time ago that I like.

**Comment by andrew-edwards** [comment]
Hi Allan - It does work, it was just commented out in the version you were using (I know that because I could check on GitHub!!), and that was because Chris would have had it commented out to run faster. 

If you download my latest commit then everything is commented in, including bibliography. There are loads of references not in there yet (though see the missing references section for ones I flagged) - I'm now tidying up the main text and ignoring references for now. 

Cheers, Andy
