### ISSUE TITLE
Can't find the correct way to plot the recruitment MLE vs. MCMC plot

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#10]
The MLE vs. MCMC plot showing biomass and recruitment with the caption:
"A comparison of MLE estimates with 95% confidence intervals determined from asymptotic...."

I can't find a subplot argument that will make the recruitment plot with bars instead of a connected time-series type.

**Comment by cgrandin** [comment]
I'm ok with it like this. Anybody really want the stick plot?

**Comment by allan-hicks** [comment]
Chris, you are the master of the document, thus you can make the call.
However, I've never been a fan of connecting annual recruitment estimates
because they are independent (or at least since we are assuming zero
autocorrelation).  I can create the stick plot, but later this weekend.
And, we already have the recruitment line plots in the document.   So, I'm
ambivalent.

**Comment by cgrandin** [comment]
I agree with you, but I've just spent another hour trying to figure out the correct way to do it with SSplotComparisons. I still can't see how. The source for that plot is make.mcmc.vs.mle.plot() in figures-mle-mcmc.r, but note it is also used for the biomass plot. subplot 8 is the recruitment case. If you just send me the function call I can put it in if you're too busy.

**Comment by allanhicks** [comment]
Sorry, I should have mentioned that it is code similar to what created the other recruitment plot. It isn't a part of r4ss. I'll try to find the code later.

**Comment by cgrandin** [comment]
This was fixed somehow. I'll just close it.

**Comment by allan-hicks** [comment]
I noticed that too. Not sure how that happened
