### ISSUE TITLE
Forecasting: All probabilities seem right except for the P(C2017<C2016).

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#11]
The probability seems to jump way up at a certain level, e.g. at 710,000 t it jumps from 0 to 100%. This is quite different from last year's results.

I am comparing the preSRG2015 model with what was in the 2015 assessment document, and the other series are the same but this one takes off. Something to check.

**Comment by allanhicks** [comment]
I agree that it is odd, but with such aggressive fishing, and a four year difference between cohorts, I can see this happening. The 2010 cohort is not adding weight to the population, so that is declining due to mortality. This is conditioned on the 2016 catch, and takign 710,000 tons of fish, removes a lot of 2010 year class, plus is aggresive on the 2014's, which will peak in 2017.  It is a good example of how aggressive the harvest control rule is.

I won't close this, but if everyone is satisfied, feel free.  I'll have a look at the code, but not sure if I'll find anything.

**Comment by cgrandin** [comment]
The code looked right to me, so I'll close this. It was something that looked wrong when I first wrote the code but appears ok now.
