### ISSUE TITLE
Survey biomass changed to 2.156 but CV didn't change

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#112]
Is this correct?

**Comment by allan-hicks** [comment]
Yes. I did not receive a new CV, and I'm not about to rerun everything with
a CV that doesn't matter.  I figured that this same CV is slightly higher
than what the new analysis would estimate, but I'm fine with that because
it is an underestimate anyways. I'll find out if Chu has a new one just to
see how different.

**Comment by allan-hicks** [comment]
To follow up on this, Chu just gave me the CV's, which for 2015 is 0.0829
instead of 0.092.  The current updated models use 0.092. I just reran the
MLE for run39 with 0.0829 and the depletion in 2016 showed a difference of
0.003, and the catch advice was different by less than 4000 tons.  This is
well within the difference observed between different MCMC runs.

So, I'll explain this by we needed to run the models as soon as possible
and didn't have the CV, and we feel that the CV is larger than 0.08 anyways
due to the fact that there is this subjective decision of whether or not
this region should be included, 2015 observed more hake mixed with other
species than any other survey, and it doesn't make a difference that we
need to worry about.

Thanks for making me think about this so that we are clear when asked.
Allan

**Comment by cgrandin** [comment]
Thanks Allan, this makes sense and given the time constraints and the low impact it has on the model, I'm happy with it.
