### ISSUE TITLE
Hard-wired percentage - Line 35, page 29

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#117]
"The most prominent of these reductions is for the 2014 year-class, where the estimated standard error is reduced by 36%."

36% is hard-wired. Not sure where to find this

**Comment by cgrandin** [comment]
In fact, there are a few after it as well, in the following paragraph (13% and 20%)

**Comment by aaronmberger** [comment]
The 36% is speaking to the reduction in error around the 2014 year class
and is hard to not hard wire.  I suggest leaving it as well as the others
in the sensitivity.  The sensitivitiy section is difficult to fully
automate because your looking at differences between model indexes which
will inevitable change year to year.

On Thu, Feb 11, 2016 at 2:26 PM, cgrandin <notifications@github.com> wrote:

> In fact, there are a few after it as well, in the following paragraph (13%
> and 20%)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/117#issuecomment-183084299>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by allan-hicks** [comment]
These are sensitivities that may never be done again. Is it worth
generalizing, or do you just want the number?

This is how you get the SD for the 2014 recruitment:

base.model$derived_quants["Recr_2014","StdDev"]

you can do similar for the age-1 sensitivity run, but I'm not sure how to
map the index to the name ("50_Sensbase_Age1Index_update")

**Comment by cgrandin** [comment]
No plans to automate this - I just wanted to make sure the numbers were correct. I noticed you (Allan) changed that line 3 days ago, so I wasn't sure if it was correct anymore, same for the other two values in the next paragraph.

**Comment by aaronmberger** [comment]
I checked those numbers last night and then inserted the "% Manual 2016
done" at the top.  Always good to double check though!

On Thu, Feb 11, 2016 at 2:36 PM, cgrandin <notifications@github.com> wrote:

> No plans to automate this - I just wanted to make sure the numbers were
> correct. I noticed you (Allan) changed that line 3 days ago, so I wasn't
> sure if it was correct anymore, same for the other two values in the next
> paragraph.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/117#issuecomment-183087542>
> .
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by cgrandin** [comment]
Ok, so they have been updated? If so go ahead and close this issue. Thanks
