### ISSUE TITLE
Feb 12, chat here about who's doing what

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#120]
At the moment, I'm going through everything and looking for inconsistencies.

**Comment by aaronmberger** [comment]
That was my plan also - take a last browse through to see if anything sticks out.

**Comment by andrew-edwards** [comment]
I'm reading through my printed version.
Maybe I'll manually switch those column names around, like all three of you did! Chris said Github didn't even query it, since the changes were identical.
And I'm thinking of adding a line somewhere saying that we used R etc. Something like:
"Calculations and figures on the output from Stock Synthesis were performed using R version .... [citation] and many packages, in particular r4ss. The use of R, knitr, latex and Github immensely facilitated the collaborative writing of this document."

**Comment by allan-hicks** [comment]
Yeah Andy, you might as well join in on the column name edits.  I like your
idea of a sentence or two explaining the tools we used.

I'm reading through the entire document and will check for other commits to
make sure I'm not dual committing, and I'll commit often. I'm still looking
for a period to commit to beat Andy's comma.

**Comment by aaronmberger** [comment]
Andy, how is the printed version looking?  I have yet to view a hard copy of anything.

**Comment by andrew-edwards** [comment]
Printed looks fine.
I think Chris's change of a colon to a semi-colon involves less pixels than my addition of a comma. He's winning.
