### ISSUE TITLE
help build sensitivity table

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#132]
I just committed a sensitivity rnw that has a frame title = Sensitivity Table - MLE.

I'm trying to generalize this so that I don't have to simply import an image of the table in the document.  However, the header on the table is not working correctly.  Any advice would be helpful.

**Comment by aaronmberger** [comment]
really the column names on the table (not header) and first frame title = Sensitivity Table - MLE (not  the second one - that is still importing the image for now)

**Comment by cgrandin** [comment]
I'll take a look tomorrow!

**Comment by cgrandin** [comment]
It's probably the font size that needs to be changed

**Comment by allanhicks** [comment]
@Chris is correct. I adjusted the font size and space size to get the table to fit on the slide.  I also made a few adjustments to the figures, and added sections and subsections so that the counter at the top shows up. You will need to latex twice to get the counters.  I worked through the mle vs mcmc section as an example. Let me know if you would like some more help.

**Comment by aaronmberger** [comment]
Cool, thanks.  Weird though cause I put the fonts super low to no avail.
Maybe space size was main diff.  And latex twice to get counters, got it,
no wonder when I did sections it didn't show up.  Learnin as I go and no
better way than by example.

Thanks again guys,

Aaron

On Friday, February 19, 2016, allanhicks <notifications@github.com> wrote:

> @Chris <https://github.com/Chris> is correct. I adjusted the font size
> and space size to get the table to fit on the slide. I also made a few
> adjustments to the figures, and added sections and subsections so that the
> counter at the top shows up. You will need to latex twice to get the
> counters. I worked through the mle vs mcmc section as an example. Let me
> know if you would like some more help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/132#issuecomment-186520128>
> .
>


-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by allanhicks** [comment]
Yeah, I had the font size down to 3, and the table was still off the slide.
It is all about the space.  I think it is fine, but you could save more
vertical space by modifying the headings, but that would require changing
the function.  I also removed the "rm" statement near the top so that it
doesn't delete the objects in the working directory.  This way, you can
load the .Rdata once (the first knit for example) and then you don't need
to do it again since it will remain in your workspace (saves a lot of
time).  So, my workflow is:

1) load the .Rdata workspace from the doc/r directory
2) change to the sensitivity directory
3) call freshtex.bat
4) knit the document (and answer "n" to load .Rdata)
5) call latex twice
6) dvi2ps
7) ps to pdf


Also, you may noticed that I modified the make.mcmc.vs.mle.plot function to
not add the 0.1 and 0.4 to the y-axis, unless it is a depletion plot. So,
you'll have to source in the function and save that workspace with the new
function as .Rdata in the doc/r directory. Or run all.r again after merging.

**Comment by aaronmberger** [comment]
closing this one

**Comment by cgrandin** [comment]
Thanks for helping solve this Allan, and I'm interested to see how you are able to run the code without having to load the RData every time. Is it that you are calling system("latex.exe") from within R?

**Comment by allanhicks** [comment]
Now I understand why you have to load the .Rdata file. You are using a batch script and the instance of R doesn't remain.  So, my workflow is to open R and run the following script:

`devtools::install_github("r4ss/r4ss",ref="cf35516")`
`require(knitr)`

`setwd("C:/GitHub/hake-assessment/doc/r") #laptop`
`#source("all.r")  #only if needed`
`#load(file="39_preSRGbase.Rdata") #this is the saved Rdata file used to create the updated doc`
`load(file=".Rdata")  #just in case I updated something, like the mcmc.vs.mle function`

`setwd("C:/GitHub/hake-assessment/beamer/SRG/Management")`
`#system("cleantex.bat")`
`system("freshtex.bat")`
`knit('beamer-hake-management.rnw')  #leave a space after this to automatically enter no`

`system("latex beamer-hake-management.tex", invisible=F, show.output.on.console=F)`
`system("latex beamer-hake-management.tex", invisible=F, show.output.on.console=F)`
`system("dvips beamer-hake-management.dvi", invisible=F, show.output.on.console=T)`
`shell("ps2pdf beamer-hake-management.ps") #have to use shell here (in Windows)`


I leave the R window open, and run only the lines I need from my editor.  This way, I can change one slide and recompile to view it in less than 30 seconds. I tend to make small changes then view, since I'm still experimenting with Beamer.
