### ISSUE TITLE
Check Figure 30 and Figure 37

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#156]
Figure 30 shows the median 2014 recr less than 2010 recr, but Figure 37 shows the opposite. The squid plot agrees with Figure 30.

**Comment by taylori** [comment]
The r4ss function SSplotComparisons used for Figure 37 uses the mean rather than the median recruitment and outputs this message: "note: using mean recruitment from MCMC instead of median because it is more comparable to MLE". Code is here:
https://github.com/r4ss/r4ss/blob/master/R/SSplotComparisons.R#L484

I will commit a change the Figure 37 caption to clarify this. Hopefully the longer caption won't prevent Fig 37 and caption from fitting on one page. I haven't yet compiled the revised document so somebody who does so should check on this before closing the issue.

In the future, we could choose to change the r4ss default, but it was specifically made the way it is to suit patterns found in previous hake assessments.

**Comment by allanhicks** [comment]
Hmmm, that is weird.  Wouldn't the median be more similar to the MLE (MPD) since it should be closer to the mode? I wrote the first bit of the mcmc code, so maybe I had a reason that now escapes me.  

For now, the caption is probably the best way forward.  Andy has a been a master at checking the document and sorting out page breaks.

**Comment by taylori** [comment]
I'm not doing a great job of coming up with the theory behind this right now, but the proof is in the pudding: 2014 recruitment in Figure 37 is very comparable, whereas if the posterior median were used, the values would look very different (based on the difference between median and mean in Figure 30).

**Comment by cgrandin** [comment]
I think the caption change is good at this stage and the document builds just fine (no extra page) so I'll close this.

**Comment by taylori** [comment]
Thanks Chris.
