### ISSUE TITLE
"above average" 2012 recruitment?

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#157]
There's some inconsistency in our description of the 2012 recruitment.

The 1-page summary notes "the estimate of the 2012 year-class being slightly above average" but the Exec Summary text says "The model currently estimates a small 2011 year class, and smaller than average 2012 and 2013 year classes (median recruitment below the mean of all median recruitments)."

This is fundamentally confusing because of the log-normal assumption used for recruitment. The median estimate of the 2012 recruitment deviation is positive, indicating that the estimate is above the expected value from the stock-recruit curve. Figure 32 also shows that the 2012 estimate is slightly above the median of the estimated distribution of recruitment at equilibrium but below the mean of that distribution, which is what R0 represents.

To avoid confusion without having to add a bunch of explanatory text (which would maybe just add confusion), my suggestion is to simply delete the phrase mentionioning the 2012 recruitment in the 1-page summary (ending the sentence after the bit about 2014 recruitment) and in the Exec Summary change "smaller than average 2012 and 2013 year classes" to "similar to average 2012 and 2013 year classes". Folks who want more detail can look at the table and figures.

**Comment by cgrandin** [comment]
That makes a lot of sense, and doesn't involve substantial additions to the text.

**Comment by allanhicks** [comment]
Yes, very confusing.  I agree that it is best to avoid too much description
as Ian suggests. "Mean" is such a poor descriptor for a such a skewed
distribution.
Thanks for catching that Ian.

**Comment by andrew-edwards** [comment]
Sounds good. I can change it if you want - just assign me.
Suggest hypenation: "similar-to-average 2012 and 2013 year classes."

**Comment by andrew-edwards** [comment]
Looks like me then. If you're done with the random assigning ;)

**Comment by allanhicks** [comment]
Sorry about all the assignments! I thought I could assign two people and was going to assign Andy and Ian.  Just wanted Ian to know that he can make changes and join the party if he wishes!

**Comment by allanhicks** [comment]
Just keeping you in suspense!

**Comment by andrew-edwards** [comment]
Ha ha - I'd actually assumed you could assign two people. Seems sensible.
I'm just source-all.r-ing so won't edit any text until everything is working.
Hmm... - it just stopped with an error though. Have to investigate...

**Comment by andrew-edwards** [comment]
error is that my hard drive is full. Again. No worries...

**Comment by allan-hicks** [comment]
Let's work out the forecast values at 10:30, so you may want to wait for
the sourcing of all.r.  I'll set up a Google hangout and anyone interested
can join. More details in a bit.

**Comment by andrew-edwards** [comment]
Is  'roughly average 2012 and 2013 year classes'  okay? Rather than similar-to-average.
I presume so...

**Comment by andrew-edwards** [comment]
Hmm.... New suggestion for Exec Summary wouldn't make sense, since existing is:

"The model currently estimates a small 2011 year class, and smaller than average 2012 and 2013 year classes (median recruitment below the mean of all median recruitments).
% ...
% AME put in definition of below-average, else it looks like it contradicts the
%  median deviations in the table.
% Allan agrees. Even though the deviation is slightly above average, the 2011 spawning biomass was small enough that the S-R curve had an effect

I think the original confusion has been cleared up by Ian's suggestion of deleting the phrase in the One-page Summary. I think the Exec Summary is good as it stands.

**Comment by andrew-edwards** [comment]
Actually, for consistency, the one-page summary should really be:

  \item The spawning biomass in \Sexpr{end.yr} is estimated to have increased from \Sexpr{end.yr-1} due to the 2014 year-class likely being well above average size.

The 'likely' wasn't there before, but is needed because of the uncertainty. Now consistent with Exec Summary text. I'll commit it so you can see.

**Comment by andrew-edwards** [comment]
Just checked - main text (p25) is same as Exec Summary. So all consistent.

**Comment by allanhicks** [comment]
I can't figure out the best way to deal with this, and now I'm thinking about the squid plot. Looking at that, you would think that the 2012 year class is above average, because it is above zero. I think that the key is to make sure to be consistent with what "average" is referring to, as I think you have done.

**Comment by andrew-edwards** [comment]
Yes, I think that's why I defined average in the Exec Summary, and why we then discussed in the comments just after that text (see my longer comment from 40 minutes ago). And we left the comments in to help us understand why we had the details!

**Comment by andrew-edwards** [comment]
Okay to close?

**Comment by taylori** [comment]
Let me read the revised text and then I can close once I've done that
(assuming it looks OK) unless somebody else objects.

**Comment by taylori** [comment]
Current text looks good. I confirmed also that the median 2012 is indeed below the mean of all medians.
