### ISSUE TITLE
Survey kriging table code wrong - repair

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#187]
Check data in table kriging-parameters.csv and the code which builds the table from it.

**Comment by taylori** [comment]
I think we should consider removing this table from the document. Since the kriging parameters for 2016 were accepted by the review panel last year, I don't think there's any need to look backwards to 2015 and before. And we can just describe the kriging parameters used for 2016 and beyond in the text rather than have a 1-line table.

**Comment by cgrandin** [comment]
That's what I was thinking also. I'll comment that code out so we can resurrect it if it becomes an issue in future years.
