### ISSUE TITLE
add figures for sensitivity groups

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#199]
Add figures for sensitivity groups 4 and 5, similar to that for groups 6 or 1

**Comment by andrew-edwards** [comment]
Will do tomorrow (maybe tonight), as will also correct the captions (they're just mixed up for now).

**Comment by andrew-edwards** [comment]
Figure \ref{fig:main-recruitment-base-alternative-2} is a density plot because that's what Fig. 43 was last year. Not sure if we shouldn't just change it to a Relative spawning biomass plot like the other sensitivities. If keep as is then need to change x-axis range. 
[I'm not quite sure why last year's Fig. 43 was a density plot and Fig 46 was a time series - maybe just Fig 43 was the main sensitivity run?]
Am working on the sensitivity figures tonight but may not push until tomorrow since I can't build it since merging earlier (and don't want to spend time tonight fixing that - I think I'll have to re-run all.r anyway tomorrow).

**Comment by andrew-edwards** [comment]
Done but need to double check captions. Have pushed since got it all built. As suspected, had to redo the forecasts due to Ian's new code, i.e. change:
                  run.forecasts = reload.all,
                  fore.yrs = forecast.yrs,
to TRUE (then back again).
And it builds! 
Let me know what you think about Fig. 43 - I think change to a relative spawning biomass one, so it's like the others.

**Comment by taylori** [comment]
I haven't built the doc or looked at the new Fig 43, but I believe that Fig 43 in the 2016 assessment was chosen as a density plot because that was the best way to illustrate that the addition of the age-1 index resulted in a similar point estimate but decreased uncertainty in the strength of the 2014 cohort. 

Pasted below are last year's Figure 43 plus a couple plots I just made using the commands
```
SSplotComparisons(h.sum,
                  legendlabels=c("Base (phi=0.20)",
                      "Less flexible selectivity (phi=0.03)",
                      "include Age-1 index"),
                  densitynames=c("Main_RecrDev_2014","Recr_2014"),
                  densityxlabs=c("Log-scale recruitment deviation in 2014",
                      "Recruitment in 2014 (billions)"),
                  png=TRUE, plotdir=mydir)

```
(where h.sum is the SSsummarize output given input of models 45, 59, and 56).

It looks like if the age-1 index were included, it would again narrow the uncertainty in the 2014 recdev a bit, and also pull the point estimate toward a similar place similar to last year (recdev =~2.3). We don't necessarily need to include a density figure like either of these, but if we find that it would help illustrate any explanations we're making of why we changed away from phi=0.03, it's something we could consider (in addition to the the relative spawning biomass plot for consistency with the others--thanks for that, Andy).

![image](https://cloud.githubusercontent.com/assets/4992918/22260168/07d2c884-e21d-11e6-9693-47537c8823a4.png)

![compare14_densities_main_recrdev_2014](https://cloud.githubusercontent.com/assets/4992918/22259978/46e514ec-e21c-11e6-92cd-cc4a39018082.png)
![compare14_densities_recr_2014](https://cloud.githubusercontent.com/assets/4992918/22259979/46e9da04-e21c-11e6-8281-e49128a92de0.png)

**Comment by aaronmberger** [comment]
I think these are important to show, probably in the document, but at least in SRG presentation

**Comment by cgrandin** [comment]
Will change 43 to reletive biomass and 46 to density of 2014 recruitment.

**Comment by cgrandin** [comment]
Also, the relative spawning biomass for bias ramp sensitivity is done, (fig 43 currently).
