### ISSUE TITLE
Are we okay saying '95% credibility interval' when really it's the 2.5% to 97.5% quantiles?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#20]
I think there's both terms in the document, but I suspect it's usually calculated as the 2.5-97.5% interval (which technically I think isn't necessarily the 95% credibility interval, or is it?). Just wanted to check, since I think we (Paul Starr and us) avoided saying 95% interval in previous assessments.

I've added something like "We calculate the bounds of 95\% credibility intervals as the 2.5\% quantile and the 97.5\% quantile of posterior distributions, to give equal-tailed intervals." to the end of section 3.6 describing the base model.

A quick look on Wikipedia (tsk tsk) says that credible intervals can be defined in different ways. So for now I'll add the text and see if anyone objects, or points out that sometimes we do actually calculate the other type, which is the highest posterior density interval but that's fiddly to calculate.

**Comment by allanhicks** [comment]
Yes, credibility intervals in Bayesian statistics can be defined in many different ways, one of which is to use quantiles.  I like this method for this assessment because we define point estimates as the median, and if we define the interval based on quantiles, we can think of this as the probability that things are greater or less than a certain point.  I think one of Gelman's books defines credibility interval in this way.

I'm going to close this, but we can reopen it if anyone disagrees.
