### ISSUE TITLE
Please clarify what needs to be re-run when just changing an option in a figure

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#209]
Chris - I'm just adding points on the biomass time series figures. Super easy to change the code, but I keep getting in a mess as to what to re-run. 
I've done source("all.r") after deleting the base case .Rdata (which I think is all that the code change should affect) and starting in a clean R workspace, and done knit(..) a few times. It worked but then I made another change and got stuck, so am just doing 
reload.all=TRUE   which usually sorts out issues (but takes a while).
Can you just clarify what steps are needed - I can add a note to the readme file (my latest has something). 
I think it worked when I did
rm(list=ls(all=TRUE)); source("all.r"); load.models.into.parent.env(); source("custom-knitr-variables.r")

but those latter commands seem to be in hake-assessment.rnw anyway, so I thought I shouldn't need to do them manually.

Just a bit confused. Can just chat tomorrow if easier......

**Comment by aaronmberger** [comment]
I'm having trouble rebuilding too but will try reload.all=TRUE approach now (BTW - in Seattle now and back online)

**Comment by andrew-edwards** [comment]
Takes a while though, and will have to do that again tomorrow I presume once Chris finishes the partest-is-no-more stuff. 
It can be done without reload.all=TRUE (though I couldn't remember exactly what I did - hence make it an issue so I can add it to readme file!).

**Comment by taylori** [comment]
In theory, changing a figure should not require any update to the Rdata files or re-running all.r, just cleaning out the stuff in knitr-cache.

The exceptions would be things like my recent bug/fix in r4ss that impacted the content of the Rdata files, or Chris's restructuring of the partest/mcmc stuff. I think once that restructure is complete, and assuming we don't discover more bugs, we should be able to add an Rdata file (potentially including mcmc stuff) for any new model without re-running any of the existing stuff.

Having said all that, Chris is the pro.

**Comment by andrew-edwards** [comment]
Aaron - if you're going to reload.all=TRUE maybe wait until I push my commit (I'll do it now - it should build fine though mine hasn't finished, and I have to go).
Ian - yes, that's what I thought should happen, but alas...

**Comment by andrew-edwards** [comment]
Okay, committed and pushed. May check in later.

**Comment by cgrandin** [comment]
I'm just on my phone here but everything Ian said is right. I've made good progress on the extra-mcmc work and I am hoping to get it finished up tomorrow morning. The testing takes a long time due to having to run forecasts and the extra-mcmc stuff. I did everything on small subsets but have to make sure it works on the full model outputs. 
Once you've created all the rdata files, you shouldn't have to do it again unless something changes. If you modify the calls to functions in knitr code chunks, it shouldn't matter unless there is a bug. I just leave an R window open at all times which has had source("all.r);load.models.into.parent.env();source("custom-knitr-variables.r") run, then just paste whatever figure code you are trying to put in a knitr code chunk into that R workspace and make sure it works. If it works in that R workspace, it will work for sure in the document. That's the easy and fastest  way to make sure the figure looks like you want it.

**Comment by cgrandin** [comment]
One other thing, if you change any of the R code (I frequently put browser() calls in figure and table functions to debug), you have to do
source("all.r);load.models.into.parent.env();source("custom-knitr-variables.r") 
again in your R workspace before the changes will take effect.

**Comment by andrew-edwards** [comment]
Chris - even those though commands are in hake-assessment.rnw?  I guess I should look into it further to understand.

**Comment by andrew-edwards** [comment]
Okay, my build works. I'll add some of those tips to the readme. I was trying to shortcut things earlier.
