### ISSUE TITLE
consider redefining "fishing intensity" for 2018

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#212]
As discussed in issues #158 and #179, there is some confusion with the current definition and we may want to consider switching to "relative fishing intensity" for the quantity which is relative to the target. Agreed that it's too late to make the change for 2017, so posting this issue with 2018 assessment milestone

**Comment by andrew-edwards** [comment]
Though currently Figure h says 'Relative fishing intensity' but the text says 'fishing intensity'. Leave as an issue and fix in one big go if we have time this year.

**Comment by taylori** [comment]
As of now, there is a mixture of uses. Figure h has "Relative fishing intensity" but Figure f says "Fishing intensity". Aaron notes that there are lots of cases, like talking about the SPR target, then "relative" shouldn't be included. Therefore, a general find and replace could change too much and Aaron will attempt a manual set of changes.

**Comment by andrew-edwards** [comment]
Aaron's useful comment from commit  161574b1   :
Note that we use relative fishing intenstity for almost everything
(i.e., because relative the target is 1 or 100%), except for we use just
plain-o fishing intensity in tables i and j and figures j and k because
we are referring to the SPR fishing intensity target directly (not in a
relative sense) where the target is 40% (not 100% as in relative case).
All this is similar to the way others think about biomass targets right,
SB40% could be a target so your refer to the 40% level, or SB40%/SB0
could be a target such that 1 (or 100%) is equating to the target.
Confusing I know, but I think it bit better now...

**Comment by andrew-edwards** [comment]
I've merged and will print out and read at least the Exec Summary, as haven't read it properly in one go. Thanks all for clarifying these definitions.

**Comment by andrew-edwards** [comment]
Have done (or suggested) all my edits for Exec Summary - nothing to major, great job everyone. Heading off for a while (6:20pm), may work a bit more tonight after 8:00pm. My new paragraph moved some tables/figures around, which I can look into later to see if that needs fixing.

**Comment by aaronmberger** [comment]
I think we sufficiently exhausted ourselves on this one for this year.  I'll keep this open buy milestone it for 2018 just to remind us to think it through one more time next year
