### ISSUE TITLE
Reload specific models

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#22]
Why do all models in the directory need to be loaded when only 1 is the base and certain sensitivities will be used. My concern is that this can be time and space consuming, especially if there are lots of models run. We are already past 15, and imagine if we were at 50 or so.

I suppose we can have a set of models that are only being used in the directory, but is it worth it to load only the necessary models?

**Comment by andrew-edwards** [comment]
With the smart loading (reload models question) that it now asks, it doesn't reload all the models each time. But, yes, it is storing all the output, meaning that the .RData file is getting pretty big. Chris's department....

**Comment by allan-hicks** [comment]
I understand the smart reload and that is really cool. What I was thinking
that we should be using the names of the model runs rather than an index.
The reason is that my models folder has many more model runs than yours.
For example I have 15.01_xxxxx 15.09_xxxx that are investigations of the CV
on the age-1 index. So, I have to sort out which models everyone else has
in their folder.  The other issue is if someone like me or Nathan wants to
build the file with a new model, but we haven't before (this is what I'm
struggling with this weekend).  We would have to download all the models
from somewhere, which can be lots of Mb's, read in all of the models, etc.
It seems to be a time-saver to read in only what is necessary. Finally,
when next year comes, and we archive only the base model, and maybe the
sensitivities, the next person can easily build the document with only hte
pertinent models, instead of archiving ever model run that we tried,
whether or not it is even reasonable.

If we use model names, we can have as many as we wish, and reload whichever
we need to reload.  Everyone can do whatever they want with their model
folders. And, it will be more obvious to us this year and the people next
year which model was the base model.  It is amazing what I can forget in 10
months time.

**Comment by andrew-edwards** [comment]
Sounds sensible. Yes, it is a bit risky at the moment requiring that everyone has exactly the same set of models in their local directory. We just have the ones from the Google Drive, but yes you will have more, but will not necessarily need us to have the also. And you still want to be able to run the knitr on such models because it will build the document for you, so you can see the effect of  a model (but we don't all need to see it).

I'll leave it to Chris, but am guessing that the best way would be to have a separate file that just lists the models we want to look at (oh, and a description of them would be very handy) and all.r then loads just those in. Once a model is no longer needed it's name and description could maybe just be commented (rather than deleted) from such file, with a short explanation of why it's no longer needed. Though I'm guessing one problem with that might be that everytime the file changes, all the models may need to be reloaded (since the previous model 3 might now be model 4), so maybe model names are needed somewhere in the code rather than just model indices. Just thinking out loud.

**Comment by cgrandin** [comment]
The way I think this should work, is that you only have the models which are relevant to the document in the models folder. So that's about 5 - 10 models. Once you've placed them in the folder, note which one is the base model, and change base.model.ind in all.r to represent that. Then, reload the project, which will load all the models (this will only take a few moments), set up the base model, do the forecasting, and create model-partest.RData. You shouldn't be changing the base model that  much, but if you want to, it's not that big a deal. There's no need to keep dozens of models in the models directory, I keep another directory called extra-models just to hold the ones not used in the document. We can talk more in the call in a bit...

**Comment by cgrandin** [comment]
The models are now referenced by name :)

**Comment by allanhicks** [comment]
Nice work!
