### ISSUE TITLE
change exploitation fraction to ages 2+?

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#233]
The range of ages that get reported as the exploitation fraction is determined by a value in starter.ss. It probably makes sense to change that from age 3 to age 2, but doing so would require re-running at least the mcevals if not other stuff, so might be better to just assign a "2018 assessment" milestone so we don't forget about it.

**Comment by aaronmberger** [comment]
Agree, we can always run one mceval for SRG or if anyone wants to see it then.  Otherwise note for 2018 sounds good

**Comment by andrew-edwards** [comment]
Agree. Just keeping this open to check that it's mentioned somewhere in Exec Summary and main text.

**Comment by andrew-edwards** [comment]
I think on hindsight I thought it not worth even mentioning in Exec Summary. Not worry about.

**Comment by aaronmberger** [comment]
Let's leave this one open, just so we remember to look at this prior to SRG (maybe even part of presentation slide).  Or at least to be done for 2018 assessment (adding milestone now).

**Comment by andrew-edwards** [comment]
We will change this year (in starter file). And check it gets defined somewhere.

**Comment by taylori** [comment]
Just changed reference age for summary biomass and exploitation fraction from age 3 to age 2 in starter file in "2018.05_change_to_SSv3.30.10" model posted to Google Drive folder. Will leave issue open to make sure we update text to reflect this.

**Comment by andrew-edwards** [comment]
So it looks like this is
```
2 # min age for calc of summary biomass
```
in 2018.19_add_2017_tv_select/    but had the value 3 in 45_Base_PreSRG_v4  last year (which I think was the base, or will be close enough).  [presumably 'summary biomass' is 'exploitable biomass'?]

So, yes, we should update the text. 

So this isn't really a full bridging step in terms of changing the model - it just changes a definition of a calculated output. So it should be mentioned clearly since it does affect the outputs (some of which appear in the Exex Summary). Presumably it's calculated this way because the selectivity is time varying and so you can't just calculate a vulnerable biomass as sum( selectivity-at-age x numbers-at-age x weights-at-age) because the resulting exploitation fraction  can change but due just to selectivity. Hopef that makes sense, just clarifying in my head. 

Should be mentioned in relation to #313.

**Comment by taylori** [comment]
I think your characterization is accurate. It doesn't look like we use the phrase "Exploitable biomass" but "Exploitation fraction" in the glossary needs to be updated to reflect the change to age 2.

Vulnerable biomass would be a good thing to calculate. I think the use of "summary biomass" is only due to the convenience of Stock Synthesis reporting the exploitation fraction = catch/summary biomass among the derived quantities (ADMB sdreport variables) for which asymptotic uncertainty and MCMC output is easily available. 

Using age 3 makes the exploitation rate look strange in years where many age-2 fish were caught, like 2016. But since selectivity is still somewhat low at age 2, using age-2 isn't that much better.

Time-varying selectivity would indeed complicate the calculation of vulnerable biomass, but we could also use the baseline selectivity (associated with the initial years of the model prior to start of the time-varying period). To get uncertainty associated with these quantities, we would need to do some calculations using the Report files in the extra mcmc output.

**Comment by aaronmberger** [comment]
I think I've updated most (all) the spots where this change comes into play, but will still keep my eye open.
Okay to close now...

**Comment by andrew-edwards** [comment]
Just re-opening to remind myself to mention it somewhere explicitly in the text (and just spotted one in a table caption - so also search the whole .tex file when doing a spell check).
