### ISSUE TITLE
Senesitivity section - extrapolation

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#241]
The second paragraph after the list of sensitivities talks about extrapolation as a sensitivity case. I believe we should remove and replace with a paragraph on Age-1 index sensitivity.

**Comment by aaronmberger** [comment]
Yeah, i was kinda thinking the same thing when I went through the first time.  We already have an age-1 paragraph which could be mostly re-purposed from last year.  This would be good since we do refer to the index as further evidence that the result from raising selectivity SD makes more sense.  I also thought we could get rid of the extrapolation part, but we still do have figures that refer to that.  Maybe we just don't cite those figures explicitly or sneak them in somewhere without having a full paragraph on it.  Just some thoughts....

**Comment by aaronmberger** [comment]
Decided to comment out extrapolation text and add age-1 index paragraph
