### ISSUE TITLE
Explain the 'default harvest policy' in the Exec Summary somewhere?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#246]
I have a few minor edits to the Exec Summary to type up now, but the only thing I think it's missing is a brief explanation of the harvest policy. The 40% and SPR_40% stuff kind of comes out of nowhere. I can probably write a couple of short sentences if people agree. Okay?

Don't want it too long as currently a lot of the tables and figures get laid out nicely with respect to the text (i.e. close to where they're mentioned). Latex will sort this out, but at present it looks good.

**Comment by taylori** [comment]
On the one hand, I think Andy has been less jaded by endless hake-related meetings so probably has the best perspective on this. However, I suspect that the folks reading this will be adequately familiar with the default harvest policy that they don't necessarily expect an explanation in the Exec Summary, especially since recent patterns in quota setting suggest that this value is not likely to be chosen as the 2017 TAC.

If we want to add something, I note that there's an explanation in section 1.3 that we could poach, in addition to the one in the glossary. I support whatever anyone wants to do.

**Comment by andrew-edwards** [comment]
Just helpful for a new reviewer or new JMC/SRG (and JTC!) members.

**Comment by taylori** [comment]
Good point. Let's do it.

**Comment by andrew-edwards** [comment]
Okay, I'll take a stab.

**Comment by andrew-edwards** [comment]
Okay, see commit c84e2b8. 

Leave this open as figures and tables have shifted I think, so I can check they're still in sensible positions (we did over-ride some of Latex's automatic placements last year).

**Comment by cgrandin** [comment]
I think it's good to have there for new people. The tables/figs look to be placed alright but I will leave to you to check and close it.
