### ISSUE TITLE
Remove table 12?

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#251]
It isn't referenced, it was from last year.
"Biomass index estimates from the acoustic survey (million t) using kriging with extrapolation,
kriging without extrapolation, and design-based methods"

**Comment by andrew-edwards** [comment]
I'd say keep it if the numbers have been updated from last year. Unless we have the survey numbers in another table already?

**Comment by aaronmberger** [comment]
Could we alter it where the columns are:
1: Year
2: Biomass estimate 2016 assessment (million t)
3: Sampling CV 2016 assessment
2: Biomass estimate 2017 assessment (million t)
3: Sampling CV 2017 assessment

This would then explicitly show the minor changes/updates from last year.  However, I'm also fine to just ditch it as we explain those minor changes in the text.  But if we did alter it, there would be a logical place to reference it.

**Comment by aaronmberger** [comment]
I don't think there is any need to reference extrapolation (with or without) this year

**Comment by taylori** [comment]
I'm OK ditching the "no extrapolation" columns. Perhaps we should also modify Fig 9 to remove the "no extrapolation" estimates. The one reason to keep these things would be that the 1995 extrapolation vs. no-extrapolation, hasn't been seen before, but given how consistent it is with the patterns for other years, I don't think that there's much value in dwelling on that.

Not to go too crazy, but what about

1. Changing Table 12 as suggested by Aaron in this thread to compare values and CV in last year vs. this year's assessment.
2. cutting Fig. 9 entirely because it's mostly redundant with Fig 8 and the revised Table 12 would show the new 1995 and 2% change in the 1998 value.

**Comment by aaronmberger** [comment]
sounds good, I like that idea.  Anyone want to take that one on?

I'd say this has to be the final 'relatively major' change for the pre-SRG version, text only changes after this !?!?   (of course unless glaring error....)

**Comment by cgrandin** [comment]
I've done what Aaron suggested. I'm just debugging it. I created a new table which is called survey-summary.csv and the code to write the new table. Not committed yet.

**Comment by cgrandin** [comment]
The way I have done it, the figure can stay the way it is

**Comment by taylori** [comment]
Great. I haven't even finished rebuilding after the merge, so clearly Chris was in a better spot to do this. I will catch up with what you've done after you commit.  The values were already present in survey-comparison.csv but an extra CSV is fine for now and we can sort things out next year.

**Comment by cgrandin** [comment]
Done - commit 9d799b62fdafe1251bca708fcf75d7cd516833f0
