### ISSUE TITLE
update workflow to be compatible with SS3.30 

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#253]
This can be done well after this years assessment is complete.  It would be nice if we could get it done by end of March or so while this is still all fresh in our mind.  Created 2018 milestone for this.

**Comment by taylori** [comment]
The challenge of this will be separating the switch to 3.30 from the need to do more with the existing repository for post-SRG edits to the text, presentations to the JMC, etc. Having looked deeper at some of the R code since we last discussed the switch to 3.30, I'm afraid that may be lots of minor edits needed to lots of functions. We could do all that in a branch, but it might be safer to put it off until after all the meetings for this year are concluded.

**Comment by taylori** [comment]
Here are a few steps I see that need to be taken related to this issue (either in a branch or the main trunk as discussed in issue #299):

1. Use the ss_trans executable to convert the 2017 base model from 3.24 to 3.30 (I've tested this previously but not with latest version, which I think is currently 3.30.08.02)
2. If we want model results to line up, considering adjusting the phi parameter related to time-varying survey flexibility to better mimic the models results (the confusing logistic transformation of time-varying parameters to keep them in bounds has gone away which makes the interpretation of this parameter slightly different) 
3. Run some MCMCs (doesn't have to be long chain to test updating the document)
4. Try to compile document (perhaps turning off some sections like sensitivities)
5. Debug

I'm happy to get started on 1-3 but am guessing that @cgrandin will be needed for 4.

**Comment by andrew-edwards** [comment]
3. Yes, run some short MCMCs, as the point is ensure the document still builds. 

Will likely need a couple of sensitivities also? And retrospectives? That may be a bit of work - I don't think there's a simple switch to omit things, but we can easily comment out parts of the document.

We should first archive the full 2017 models (as in #299) on our computers, and then work with these 'dummy' results that just use the latest SS3. Remember the branching will refer to the R/knitr/latex code, but not the models/ folder since that isn't tracked in GitHub (too big) - we have to manually make sure we're using the same model results.

**Comment by taylori** [comment]
Clearly we'll need to test the sensitivity and retrospective sections eventually, but ideally we could configure the document to compile even with some sections missing.
Or perhaps we just need to do more unit testing (if that's the right term) to ensure that individual pieces are working even if the whole thing isn't yet complete.

**Comment by cgrandin** [comment]
I'd like to test the sensitivity and retrospectives sooner rather than later as there's lots of code that can break there and I'd rather not have the pressure near the due date. Just 2 sensitivities would be fine, and probably the full retrospective set for the base model.

**Comment by taylori** [comment]
I'm currently uploading models to "Hake JTC 2018/models" folder on Google Drive. These models are described in a README spreadsheet in the same folder. I went ahead and ran a full-length MCMC for the SS version 3.30 model that best matches the 2017 base since I started it over the weekend.

The match of the converted model isn't perfect for one specific reason. SS version 3.30 no longer has the option to apply a logistic transformation to time-varying parameters to keep them within bounds as the potential benefits of this option didn't seem to outweigh the confusion and difficulty in interpreting the parameters that it caused. However, since the option was used for hake, it's difficult to perfectly mimic the model after conversion. I manually adjusted the phi parameters controlling the flexibility of the time-varying selectivity until the spawning biomass timeseries was a reasonable approximation. Since we're considering exploring alternative selectivity setups anyway, I'm not sure a more precise match is worth spending time on.

**Comment by cgrandin** [comment]
This will take some time. SS_readdat_3.30 doesn't work for these data files so I'll have to debug that before starting.

**Comment by taylori** [comment]
Sorry, I have uncommitted changes to SS_readdat_3.30 that are in process from long ago. I will try to get those pushed to r4ss on github ASAP.

**Comment by taylori** [comment]
I just committed the changes, but they may not have been related to the problem you're seeing as I was able to run 
dat <- SS_readdat_3.30(file="C:/github/hake-assessment/models/02_2017base_3.30/2017hake_data.SS")
without error.
However, one of the changes in format of the data files for SS version 3.30 is that the count of data inputs is no longer present in the data file and each section ends with a terminator row starting with -9999. Therefore the $N_cpue element is no longer present as expected in this line: https://github.com/cgrandin/hake-assessment/blob/master/doc/r/r-functions/load-models.r#L988

It would be possible to add that element to the list, but I think it might be simpler to just change the code from `model$dat$N_cpue` to `nrow(model$dat$CPUE)`.

Let me know if I'm missing something or how best I can help debug.

**Comment by cgrandin** [comment]
I'm doing this in R:
devtools::install_github("r4ss/r4ss")

But I'm not sure if that is getting the newest version. Do you know?

**Comment by taylori** [comment]
It SHOULD be getting the newest version.  Version number was incremented to 1.28.0 about 3 weeks ago:
```
packageVersion('r4ss')
[1] '1.28.0'

```
Perhaps I need to do a clean install to better check for issues as I have a few other things in process.

**Comment by cgrandin** [comment]
I have that version but the SS_readdat_3.30 function needs extensive changes to make it work. It's trying to read in a completely different file format than what we have for hake.

**Comment by taylori** [comment]
I just downloaded the file 2017hake_data.ss from Hake JTC 2018 / models / 02_2017base_3.30 and ran the function and it worked:
```
> test <- SS_readdat_3.30('C:/Users/ian.taylor/Downloads/2017hake_data.ss')
Running SS_readdat_3.30
SS_readdat_3.30 - SS version = 3.30
use_meanbodywt (0/1): 0
N_lbinspop: 
use_lencomp (0/1): 1
N_lbins: 26
N_agebins: 15
use_MeanSize_at_Age_obs (0/1): 0
N_environ_variables: 0
Read of data file complete. Final value = 999
Warning message:
In SS_readdat_3.30("C:/Users/ian.taylor/Downloads/2017hake_data.ss") :
  The supplied data file has 1 section.  Using section = 1.
```
Could it be an issue of mixing up the 3.24 and 3.30 versions of the files? I probably should have renamed the converted files. The 2017hake_data.ss in 3.24 format has a first line that reads
`#C 2017 Hake data file`
while the one converted to 3.30 format says
`#V3.30.08.04-trans;_2017_11_08;_Stock_Synthesis_by_Richard_Methot_(NOAA)_using_ADMB_11.6`

**Comment by cgrandin** [comment]
Me too and it worked. It's because I was trying to read 00_45_2017base, which I thought was the 3.30 version of last year's model. So I think it's ok

**Comment by taylori** [comment]
Sorry about that. The 00_45_2017base folder is just an identical copy of the 45_BasePreSRG_v4 folder in the 2017 directory. I just updated the README spreadsheet to note that this is still in 3.24 format.

**Comment by cgrandin** [comment]
It's OK, I should have figured it out from the fact that it didn't have the 3.30 part in the folder name. Phew, I thought I had to rewrite the whole thing again.
