### ISSUE TITLE
Revisit MCMC diagnostic plots

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#288]
We should revisit the display and discussion around MCMC diagnostics.  Is what we have sufficient?  What else should be included?  Does MCMC work completed by Cole Monnahan (Trevor Branch student) have any significance to these decisions (MCMC diagnostics and/or MCMC runs and/or software, etc...).

**Comment by andrew-edwards** [comment]
I know Cole gave a talk the other week that I didn't sit in on, but I think nothing is published and so wouldn't have any bearing. I think Trevor mentioned that it might not even work out, and since he didn't give us an explicit reference I don't think we need to include anything.
Maybe, yes, just check the diagnostics text again, and update main text to point to the new Appendix.

**Comment by aaronmberger** [comment]
Yep, that is all I'm doing via #278.  I labelled this one for milestone 2018 just to remember to look at (if anything) comes out of that work as well as revisit mcmc diagnostics next go around.

**Comment by taylori** [comment]
Cole's improvements to ADMB just being merged into main ADMB for testing now. Not ready for 2018 hake assessment.
Leaving open to remind us to at least research what the status-quo diagnotics means so we can answer any questions if they happen to arise.

**Comment by aaronmberger** [comment]
Look at Cole's recent work to see what MCMC diagnostics he uses

**Comment by aaronmberger** [comment]
Cole's adnuts package looks like it allows for rstan package MCMC diagnostics to be used with standard -mceval admb output.  This will need further examination and testing, but hopefully will add to the standard MCMC diagnostics produced by the coda package that we currently use.

**Comment by aaronmberger** [comment]
I haven't done anything with updating ss with new version of ADMB that would likely allow our use of Cole's adnuts package, so not doing anything further on that.  

I did compare two separate mcmc chains and the diagnostics look good.  Output probably just useful for SRG discussion, rather than inputting into assessment document.

[KeyParameterTrace.pdf](https://github.com/cgrandin/hake-assessment/files/1698019/KeyParameterTrace.pdf)
[KeyParameterGelman.pdf](https://github.com/cgrandin/hake-assessment/files/1698021/KeyParameterGelman.pdf)

**Comment by aaronmberger** [comment]
The within chain and among chain variance is compared using a shrink factor, and typically anything less than 1.1 or 1.05 is considered good in terms of convergence.  Just comparing some key posterior values here, but also did all the nuisance parameters as well.  bottom-line = no worried about convergence, similar to what our standard single chain diagnostics indicate.

**Comment by andrew-edwards** [comment]
Thanks Aaron - yes, they seem to look good. 
Is it worth including in the document (given you've made them)? Can just put them in as they are (if you can make .eps), rather than automate them (just don't tell Chris).
Or, yes, just show at the SRG. Which will be easier, but I kind of feel if it's worth showing at the SRG it's probably worth having in the document.

**Comment by aaronmberger** [comment]
I just uploaded eps files for these into the main-figures folder.  We can eventually decide if we want them in the document or just for SRG presentation.  I could go either way, but originally thought just for SRG discussion.

I think this issue can be closed for now, but (I) need to remember to do a memory refresh of all diagnostic plots before SRG.
