### ISSUE TITLE
grey (gray) text

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#30]
The text in the pdf seems to be a dull gray which is difficult to read (at least on screen). Can the main text be black? Or, is this related to how I tex'ed my version of the document?

**Comment by andrew-edwards** [comment]
I think the default latex font often comes out a little like that - I'm okay with it but probably just used to it! 

To change font, just add

%https://www.sharelatex.com/learn/Font_typefaces  
\usepackage{tgschola}

on line 61 of hake.sty   .    The commented website lists a bunch of fonts, and the tgschola is one example. (I emailed Allan an example page). I don't particularly like that one, but we can play with other ones if necessary. I'm just using ps2pdf, I'm not sure if's related to whoever is making the pdf.

**Comment by andrew-edwards** [comment]
Based on a quick fix suggested on
  http://tex.stackexchange.com/questions/7185/how-to-make-the-pdf-output-of-better-print-quality

I tried  \color{black}    before a piece of text, and the text after that does indeed look a little darker (at least in .ps, presumably in the .pdf also).  I tried putting it after \begin{document}, and it mainly works, except for captions and later text. I can look into it.

Also, opening the text of the .ps file in Emacs, there are 8764 instances of the word 'gray' when I did not have \color{black} at the start, but (confusingly) 9092 when I did have \color{black} at the start. I was hoping there would be less grays.

Anyway, I can probably fix it (doing a global thing, rather than \color{black}), and ensure captions etc.

**Comment by minnowslayer** [comment]
I had the same trouble with the greyish font.

**Comment by andrew-edwards** [comment]
I've tried quite a few things, but can end up running into technical issues regarding embedding fonts in .pdf. Have just made the default color black [ \color{black}   before \begin{document} ]  but don't think it actually made a difference in the .pdf, but did in the .ps. Have commented it out.
The issue with the tgpagella font was that it was pretty poor when printed out. 

Suggest sticking with the default font, which Chris and I are fine with, even though it can be a little thin. We know it won't mess up.

**Comment by allan-hicks** [comment]
Fine with me. Nit picky things that we don't want to get too hung up on.

**Comment by andrew-edwards** [comment]
I'm still (annoyingly) getting hung up on it - my printout wasn't great. But a recent manuscript (using default font) printed out fine. We have lots of packages that I don't think are used (hangovers from earlier projects). I found a Times New Roman but it messed up the math. One more thing to try then I'm definitely done with messing around with fonts.....
