### ISSUE TITLE
SS_readforecast doesn't work for SS 3.30

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#300]
"sorry, SS_readforecast doesn't yet work for 3.30 models with catch caps or allocation groups"

**Comment by cgrandin** [comment]
It'll also mean fixing SS_writestarter. It looks like there is more input added to the bottom of the 3.30 version file.

**Comment by taylori** [comment]
There were 2 issues with the read/write forecast functions in r4ss. The first was an extra line about "Forecast selectivity" which I've corrected in this commit https://github.com/r4ss/r4ss/commit/464273a217a4e7d24cbd226cd66d4ab12090a73b

The other is the problem with the caps and allocation groups. As a short-term solution, rather than deal with fixing the r4ss functions, I confirmed that the forecast file for our model can be simplified and produce identical results since we don't actually need any allocation groups (a feature only required for allocating multi-fleet models). 

Changing these lines in 03_2017base_3.30_tv_pars/mcmc/forecast.ss got things working for me:

**CURRENT:**
```
# enter list of fleet number and allocation group assignment, if any; terminate with fleet=-9999
1 1
-9999 -1
#_if N allocation groups >0, list year, allocation fraction for each group 
# list sequentially because read values fill to end of N forecast
# terminate with -9999 in year field 
 2017 1
 -9999  1 
2 # basis for input Fcast catch: -1=read basis with each obs; 2=dead catch; 3=retained catch; 99=input Hrate(F)
```
**SIMPLIFIED:**
```
# enter list of fleet number and allocation group assignment, if any; terminate with fleet=-9999
-9999 -1
#_if N allocation groups >0, list year, allocation fraction for each group 
# list sequentially because read values fill to end of N forecast
# terminate with -9999 in year field 
2 # basis for input Fcast catch: -1=read basis with each obs; 2=dead catch; 3=retained catch; 99=input Hrate(F)
```
