### ISSUE TITLE
Glossary per-recruit figures broken

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#302]
The three figures for Numbers per Recruit, Biomass per recruit, and Female spawning biomass per recruit

**Comment by taylori** [comment]
Thanks for flagging this and other broken stuff. I should have time to help debug tomorrow afternoon.

**Comment by andrew-edwards** [comment]
I thought they were just simple plots - should be an easy-ish fix (I think we may have done something funny last year; maybe the code isn't actually in there).

**Comment by taylori** [comment]
I think I got this sorted out in commit e9130c6. 

This and surely other yet-to-be-discovered issues with converting to SS version 3.30 are related to making terminology more consistent (e.g. "Year" became "Yr") as noted here: https://github.com/r4ss/r4ss/issues/141#issuecomment-292611174.

I'm not yet able to run build.doc due to some LaTeX errors about missing .sty files and MikTex is telling me "Couldn't connect to server" for some reason. So I will leave the issue open until we confirm that the figures are properly created
