### ISSUE TITLE
Add linebreaks to document to improve git change reviews

### ISSUE THREAD

**Issue by taylori** [cgrandin/hake-assessment#305]

**Comment by andrew-edwards** [comment]
And then add ** to each paragraph that needs manually editing/thinking about.

**Comment by andrew-edwards** [comment]
I'll do as separate branch 'linebreaks' which I can then merge. I'll highlight text and use
```Alt-x-fill-region```
in Emacs to force line breaks after 80 characters. Two things to be aware of:
1. if searching a file for a phrase of text it may no longer show up because the phrase will get split over two lines (but may be sometimes split anyway) - but it is preferable to see changes more easily on GitHub.
2. Any comments [% .....] at the end of paragraphs may get uncommented if the %  happens to get put on the line before. I had this happen before and easily spotted it, but kind of think might not have any/many - sounds like the sort of thing Chris wouldn't allow ;)

**Comment by andrew-edwards** [comment]
And only for text - I won't touch any computer code. That likely doesn't run on for several lines.

**Comment by taylori** [comment]
I think your plan sounds good.
I also don't expect many comments at end of paragraphs and figure this will reveal them quickly. Someone better at regular expressions could theoretically search for instances of " %" with no linebreak between the space and the %.

**Comment by andrew-edwards** [comment]
I didn't expect many either - then found two on the one-page-summary ! Easy to check - I just rebuild and compare the .ps with the earlier version.

**Comment by andrew-edwards** [comment]
Fiddly but worth doing, as can be seen at the top of https://github.com/andrew-edwards/hake-assessment/commit/38e470bfec80ff30417ddd3f93d8d355517eea4e 
Any future changes will be easier to understand.

**Comment by andrew-edwards** [comment]
Have finished but need to double check the .ps tomorrow (easier at work on big monitor). Then I'll merge my linebreaks branch back into master.

**Comment by andrew-edwards** [comment]
Checked my changes - had introduced one extra space, fixed in d5853a3 and merged back into master.
