### ISSUE TITLE
11pt font

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#31]
Allan prefers 11 pt font.  Should we change the documentclass argument to 11pt instead of 12pt? It will save some pages.

**Comment by andrew-edwards** [comment]
Personally I prefer 12pt as it's easier to read, especially with subscripts (a prof once told me to always do a resume in 12pt so it doesn't put off people with poorer eyesight).
Also, Chris has formatted tables etc. to fit on pages, and messing with the font may make the tables smaller than necessary (because the font he used may have been relative to the default).
An easier way to save two pages of text is to not repeat the "Research and data needs" in the main text  ;)  Is there any point to having it twice?? The whole subsection looks to just be copied and pasted.

**Comment by allan-hicks** [comment]
Sounds reasonable to me, plus we have reduced the page numbers quite a bit
in recent years.

As for repeating sections, I feel like the Executive Summary and Main
document should be stand alone.  We could summarize the research
recommendations to the top 3 or 5 in the Executive Summary, and/or give
shorter descriptions. Then it would actually be a summary.

**Comment by andrew-edwards** [comment]
Seems sensible to just have the main (3-5) ones in the summary. 

If we do want them all we can just have one .tex file that gets imported twice - easy to do. But the main ones seems better.

**Comment by andrew-edwards** [comment]
I made a single file for research needs that gets called by Exec Summary and the main text (so only needs to be edited once). Do we want just the main (top 3 or 5) in the Exec Summary - easy to do. I'd forgotten that you suggested just having the main ones (I thought that was Chris...). 
I'd suggest top 3-5...
