### ISSUE TITLE
make.parameters.estimated.summary.table() function broken

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#324]
This is because it parses the control file to get all the prior information and everything, so it'll have to be re-written since the structure of the control file changed for SS 3.30.

It is called in the `custom-knitr-variables.r` file

**Comment by andrew-edwards** [comment]
Is this different to Issue #317. I think that was the only Table that I didn't have building last week (not to say other tables won't build now).

**Comment by taylori** [comment]
Yes, the order and naming of the columns in the control file has changed slightly between 3.24 and 3.30.

A bigger change, but more robust to alternative model setups, would be to rely on the model$parameters output rather than read anything from the control file.

The columns in $parameters include `Label`, `Value`, `Phase`, `Min`, `Max`, `Prior_type`, `Prior`, and `Pr_SD`, which I think would provide all that's required to fill in this table, where the `Label` value could be used to separate the different parameter types.

**Comment by cgrandin** [comment]
That would have been a better idea but I already fixed it using the control file, so I might just leave it.

As it stands, the build won't work. I am working on getting it going and made some commits but there's no point in me pushing them until it works, which I hope will be tomorrow. Also, I'm trying to make it so we can switch the assess.yr to 2018. I'll post an issue about how to build everything once I have it done.
Thanks

**Comment by taylori** [comment]
Sounds good. Thanks for working on this.
