### ISSUE TITLE
No TV selectivity output for 2017

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#326]
It only goes to 2016 in posteriors.sso for the temporary base model

**Comment by taylori** [comment]
Dang. Good catch.
Yes, lines 191-195 of 2018hake_control.ss need to have the 2016 changed to
2017.
We could just call that another step in the bridging process and upload a
model 2018.19 with the change.
-Ian

**Comment by aaronmberger** [comment]
That sounds like a good plan, and perhaps will be advantageous given the SRG comments about last year's process for setting phi and how that affects this year, etc...

So will the 2018.19 be the new base then or just repeat it that run and call it 2018.20 temp base?

**Comment by taylori** [comment]
In the few seconds since posting to the other issue #325 I've come to think that the duplication for temp base is not needed since `base.model.dir.name` in https://github.com/cgrandin/hake-assessment/blob/master/doc/r/model-setup.r will identify which is the base at the moment.

**Comment by cgrandin** [comment]
That's correct Ian

**Comment by aaronmberger** [comment]
and the model didn't need any further tuning so left it tuned to that equal to models 2018.18 and equivalently 2018.17

**Comment by aaronmberger** [comment]
What is the SD on the time varying deviation for selectivity in our current temp base model (2018.19_add_2017_tv_select)?  The 2015 base model used 0.03 and our 2016 base model used 0.2.  I'm not familiar yet with the ss3.30 parameterization of this SD

**Comment by taylori** [comment]
In converting to 3.30, the 0.2 because 1.5 via trial and error. I described the reason for the change starting around line 298 of assessment-section.rnw: https://github.com/cgrandin/hake-assessment/blob/master/doc/assessment-section/assessment-section.rnw#L298

Instead of being a fixed value as one of the many columns in the long parameter line, the SD is now a separate parameter with label like "AgeSel_P3_Fishery(1)_dev_se", starting on line 233 of the 2018hake_control.ss (below the selectivity parameters). In theory it could be estimated, but I think Jim Thorson has said that the suggests that the estimation would be biased and we need to use the Laplace Approximation method if we want to estimate this value (and the matching ones for each age). Also, there is now an option to estimate an autocorrelation parameter for the time-varying effects, but I think that given the hypothesis of cohort-specific targetting, the autocorrelation within each age over time wouldn't make sense.

Unfortunately, I'm not sure if Jim Thorson's Laplace Approximation code works with SS 3.30, but I think we could provide over the parameter and repeat those calculations if needed.

**Comment by aaronmberger** [comment]
Okay, thanks Ian.  So it may be bit more difficult if we want to reproduce our 'phi' sensitivity runs from last year.  But we can easily still select a phi slightly higher and lower if needed as sensitivities.  And perhaps, if we go with the new non-parametric approach it will be less important.  Though I imagine the SRG will want to see those runs for comparison (????)

**Comment by taylori** [comment]
After putting together the bridge models 2018.11 through 2018.18, I worked on the write-up and illustration of the parameter transformation (or rather, the removal of a transformation) required for that conversion (illustration attached that was previously shared by email--I will attach all the emailed files to a comment on issue #309). The slope of the linear part of the line in that graphic, given the bounds of -5 and 9 that we have in place for the selectivity parameters is 0.1485. This suggests that a closer match to the old phi=0.20 would have been a new phi = 0.20/0.1485 = 0.135, rather than 0.150. But I think the differences are small enough that it wouldn't be worth re-doing all the bridge steps.

Confusingly, that conversion suggests that the equivalent of the pre-2017 phi=0.03 would be phi=0.03/0.1485 = 0.202 (that is, close to the 2017 value).

![selectivity_transformation_illustration](https://user-images.githubusercontent.com/4992918/35357325-05b1f4d4-0108-11e8-8cc7-677422c62d6e.png)
