### ISSUE TITLE
Helpful to include B_MSY in Table 26

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#335]
Am also thinking we should include somewhere P(B>0.4 B_MSY), P(B>0.8 B_MSY) and P(B>B_MSY) for the current biomass. These are (provisional) DFO reference points, and having them calculated would be useful for Canadian purposes (to say whether the probability of the stock being in the DFO 'healthy zone').

**Comment by aaronmberger** [comment]
Agree!

**Comment by andrew-edwards** [comment]
B_MSY is actually in Table 27 (think it didn't build when I made this issue), so no need for it in 26. I'll do the probabilities if time, and maybe just put them in some text somewhere. Not necessary if don't get done.

**Comment by cgrandin** [comment]
Done in commit 7ee022fa697aefd5ab6d70408f2848fa1b851a86.

Everyone must delete the base model RData file and do `source("all.r");build()` because the risk tables code removes the last three columns of the `base.model$risks` dataframes, so you need the new ones.

Look at the last two lines of `custom-knitr-variables.r` to see the new variables `dfo2018` and `dfo2019`, which are 3-column dataframes of the reference points Andy mentioned above.

**Comment by andrew-edwards** [comment]
Thanks Chris. I'll re-open this just so I remember to add some text in.

**Comment by andrew-edwards** [comment]
Text can go in 3.6 Ref points. I'll steal some from a POP assessment.
