### ISSUE TITLE
Presumably Table 14 and Fig 9 can be simplified

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#337]
Last year's assessment: Table 14 and Fig 9 had the 2016 assessment's and 2017 assessment's acoustic survey estimates, because the 1998 value changed. Presumably no need for 2016 values in the current assessment - i.e. just need 2018 columns in Table 14 and no red 2016 bars in Figure 9.
Also penultimate paragraph on page 34 (regarding revised 1998 data being used in 2017 but not 2016) can just be deleted.

**Comment by andrew-edwards** [comment]
Could in theory just combine Figures 8 and 9, but it's probably best to keep Figure 8 as a standalone figure showing one survey biomass estimate for each year (other people may want to use that in other contexts).

**Comment by taylori** [comment]
I agree on the simplification. It might be good to keep the extra column in the CSV file and just remove it from what gets included in the table so that if there are future changes in survey work-up that apply to multiple years we could rely on it again.  Then again if/when that's needed, we can always expand CSV.

I'm OK either either combining Figs 8 and 9 or keeping separate.

**Comment by cgrandin** [comment]
Completed in commits 9360d41a9ebada8a2350fc94320164abd7d990ad and 57bf631b9458a1dd9006a485ee6ac5b8d5d341af

**Comment by andrew-edwards** [comment]
It's best (and easier) to keep Figs 8 and 9 separate. Also it's helpful to keep figure numbers the same as they were last year for consistency. Towards the end this might not be possible (with different numbers of sens/bridging figures maybe). Anyway, issue closed.
