### ISSUE TITLE
Add tickmarks in Fig 28 , 29 (and prob others) like in Figure 34

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#341]
Fig 28 currently forces 2018 to be added on, but it overlaps with 2020. 
Much clearer (and more standard) to have tickmarks like in Figure 34. I don't mind doing it (at some point). Tickmarks make it easy enough to check what the final plotted year corresponds to.

**Comment by cgrandin** [comment]
Or we could just stop 2020 from being shown on the axis

**Comment by andrew-edwards** [comment]
Personally I find the non-uniform tick labelling a bit jarring, though I know people are used to it in hake. With tick marks it's fairly clear to see the final year (and all the earlier ones). E.g. look for 1983 in Fig 31 v Fig 34. But I'm okay either way (and don't want to change everything if people then want it back to the usual). Having said all that, I see that for Figure c it does clearly highlight the final year. 

Simple solution is to force the axis to be what xlim is set to - xaxs="i"   I think.  (And also add  0.5 to the max of the x-axis so the final year isn't right on the right-hand axis). Then 2020 won't show up, even next year. I can have a play at some point (and sneak in the tickmarks!).

**Comment by taylori** [comment]
I'm good with the style of individual years getting unlabeled tick marks as proposed if somebody has time and interest to go through and make that change.

However, just reporting here that for the assessment histories plot, there's a switch to specifically check for whether the end year is too close to the next multiple of 10, and leave off the label if it is:
```
  # add x-axis mark for final year (without label if too close to nearest decade mark)
  axis(1, at=max(years), label=ifelse(max(years)%%10 < 2, "", max(years)))
``

**Comment by andrew-edwards** [comment]
Good to know - maybe we just use that elsewhere to make the final year show up. Thanks.

**Comment by taylori** [comment]
Ironically, I posted that comment about the conditional label on the tick mark while editing the function before actually looking at the updated graph. The `ifelse(max(years)%%10 < 2, "", max(years))` only works if the end year is just AFTER the interval of 10, not just before. I fixed it to go both directions, but found that adding an unlabeled tick mark at 2018 just looks strange.

Instead, I think it looks best to just add extra short ticks for all years (adding the extra ticks up to 2018 looks strange because of a gap in 2019 before the bigger mark at 2020)

The command I used was 
```
axis(1, at=1950:2030, labels=rep("", length(1950:2030)), tcl = -0.3)
```

**Comment by cgrandin** [comment]
Completed in commit b07f52690836065b6aac4cc7bb76729b5fbb496e.

Figures 30 and 31. I put the Unfished equilibrium text a little below the axis tick labels and added the year (1964) to the text. Let me know if anyone doesn't like it and we can remove that or do something else.

**Comment by andrew-edwards** [comment]
The unfished equil is a little unclear (and it's a bit confusing to mention 1964). 

I have a feeling it's tricky to force the x-axis to start ticks at 1966, yes? Then the unfished would be more clearly separate. Hmmm... don't want this to take time (a quick back-up option is to revert the commit (I think Chris said he did it all in one on purpose), and just force the xlim for now to stop at 2019 (xaxs="i"). Sorry for not checking this earlier.

**Comment by taylori** [comment]
Looking at Chris's commit b07f52690836065b6aac4cc7bb76729b5fbb496e, it's done in a clear and easy to understand way, so it should be quick to edit to start ticks in 1966. I can do that this evening.

**Comment by taylori** [comment]
Change completed in commit 8e2a62b. It requires `source(all.r)` because `model-setup.r` now contains controls over the big and little ticks. @andrew-edwards if this isn't what you were looking for, feel free to modify or suggest changes as you wish.

```
# tick marks for time series plot
big.ticks <- seq(1970, end.yr+4, 5)
little.ticks <- start.yr:max(big.ticks)
```

![image](https://user-images.githubusercontent.com/4992918/36084660-271bd296-0f74-11e8-9933-e4bc957845cb.png)

**Comment by andrew-edwards** [comment]
Perfect, thanks!
