### ISSUE TITLE
Un-hardwire scale of largest bubble in caption of Figure 33 (bubble plot of ages)

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#343]
Should be easy enough to extract (all values are given in Table 20).

**Comment by taylori** [comment]
Biggest bubble should be calculated as largest value in the numbers-at-age table (filtered for beginning of year and not middle of year:
```
1000*max(base.model$natage[base.model$natage$"Beg/Mid"=="B", paste(0:20)])
```

Separately, I'm surprised that the figure is working as the document is maybe relying on the version of SSplotNumbers at https://github.com/cgrandin/hake-assessment/blob/master/doc/r/SSplotNumbers.r
rather than the r4ss version which has gotten a variety of updates. I did a comparison of the two (using the version of the r4ss file printed to the console, and there are tons of changes, but I couldn't find one specific to the needs for hake. I would suggest, if you haven't already done so, that we try the r4ss version and if it doesn't work, then modify it as needed within r4ss to avoid keeping out of sync (which made sense at the time but now we have a chance to fix it).

**Comment by andrew-edwards** [comment]
No, we over-ride the r4ss version:
https://github.com/cgrandin/hake-assessment/blob/23ac18e8e97c1db3996a8c7347c785bb506a5e60/doc/r/SSplotNumbers.r
which Chris added in November.

**Comment by taylori** [comment]
My confusion was due to thinking that the hake-assessment version SHOULDN'T work with the base model in 3.30. However, running it now, I see that since we have a single-sex model and aren't sub-setting for males or females, then the change from Gender to Sex in the column names doesn't matter. We could reducing duplicate code in the future but since the fig works, I see no need to change at the moment.

I just made the caption dynamic in commit 632b4fe, where to get the value in billions, the calculation was
```
round(max(base.model$natage[base.model$natage$"Beg/Mid"=="B",paste(0:20)])/1e6,1) 
```

I haven't built the doc to test the change, so will leave open until someone confirms that this worked correctly. Feel free to round to different than 1 decimal place if you wish.

**Comment by cgrandin** [comment]
You just forgot the Sexpr{} so I added it in commit 75e885f198a6dd73f79b99f81c5cb803b4cb7b97

**Comment by andrew-edwards** [comment]
Me too. Am fixing the conflict. The 1980 should also be automated - am working on that now, though maybe Chris will beat me too it again ;)

**Comment by cgrandin** [comment]
No, go ahead!

**Comment by andrew-edwards** [comment]
Leaving 1980 as is for now. It's correct, but fiddly to automate. Leave the ** in caption so we do check it's still true for final base model.

**Comment by taylori** [comment]
Since the bubbles represent numbers, which can only decline after recruitment (as opposed to the biomass of the cohort), the biggest bubble should always be age-0 for the year with the biggest recruitment in the time series of MLE values. We should be able to calculate that as 
\Sexpr{base.model$recruit$Yr[which(base.model$recruit$pred_recr==max(base.model$recruit$pred_recr))]}

**Comment by taylori** [comment]
Went ahead and committed change as part of 9b28cd1, seems to work (I find did the build(T,T,T) and build.doc() to check), so now closing issue.
