### ISSUE TITLE
Sens plots (Figs 43 and 44) for full bias ramp adjustment - need years in captions automated (or manually changed when change sens run).

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#345]

**Comment by taylori** [comment]
This figure may change or be removed due to the revised bridging path, so probably not worth investing in automating the captions.

My suggestion for how to represent the bridging is to combine the adjustment of the bias adjustment with the addition of the fishery age comps, as described in what's currently lines 351-360 of assessment-section.rnw https://github.com/cgrandin/hake-assessment/blob/master/doc/assessment-section/assessment-section.rnw#L351

As noted in section #313, the bridging text needs expansion to include description of the impact of each step and reference to figures, so this figure and its caption can be removed or revised at that time.

Perhaps we should settle on a base model first and then finalize the bridging steps it took to get there after that.

**Comment by taylori** [comment]
Bias ramp adjustment folded into bridging step "Add 2017 fishery ages and updated associated settings related to recruitment" and no longer called out in figure. However, this issue helped me remember to fix some other things in the captions of the bridging model figures (commit f40572f). Should now be safe to close.
