### ISSUE TITLE
No individual MCMC sample lines on plot

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#353]
This is figure 21 currently, the one with MLE and median MCMC and individual MCMC sample lines for the fits to the survey index.

**Comment by taylori** [comment]
I noticed that too but failed to follow up.
I think I just fixed this in commit 612dd53 which changes ss3.par to ss.par in load-models.r. The hard-wiring of the ADMB output files as ss.* also involved hard-wiring ss.par, regardless of executable name. I haven't yet re-run to comfirm, but I think this will fix it, as the .par files in the extra-mcmc directory are all the same.

**Comment by taylori** [comment]
Should now be fixed in commit 642b7d8 but will leave issue open until `build(T,T,T)` finishes and I confirm that the plots look right.

**Comment by taylori** [comment]
Plot now sorted out. In addition to fixing the read of the extra-mcmc report files, there were some minor changes needed in figures-mcmc-diagnostics.r, which were made in commit decfc06. I also added an option to subset for a fixed number of lines in the plot, rather than showing all samples, with default = 1000 because 2000 lines just because a big blue blob.

Plot looks as below:
![image](https://user-images.githubusercontent.com/4992918/35773412-6dbdec58-0906-11e8-81da-2fe8439fb657.png)
