### ISSUE TITLE
Dat file survey timing (0.5?)

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#355]
Does an entry of 0.5 (see below table; sounds like SS3.30 ignores values of 0.5 anyway) then default to a timing that corresponds to the month entered for the survey (or fishery).  I would have thought that we would have put a 7 for the survey instead of 0.5, but maybe a 0.5 defaults to that specified in the survey observations section (which is month=7).  Probably fine, but just wanted to make sure.   

#_fleet_type timing area units need_catch_mult fleetname
  1          -1     1    1     0               Fishery  # 1
  3          0.5    1    2     0               Acoustic_Survey  # 2

I can easily run a check, but figured I'd ask first.

**Comment by taylori** [comment]
I don't know why this input is set up this way, but it's definitely confusing.
The "timing" input here is really about what fraction of natural mortality occur before and after any catch is removed, so it's not really about observed data, and maybe that's why the input isn't a month value. With SS 3.30, there's now a -1 option (and warning if you use a fraction instead) for fisheries, that cause the F and M values to both occur continuously throughout the year. Since our survey has no catch associated with it, I think the 0.5 is ignored. Chantel tried adding survey catch for the POP model and I it didn't actually get removed from the population. I'm not sure if that's been fixed or not.

Short answer, I think what we've got for hake is correct, but the new -1 setting for the fishery represents a tiny change from previous models that perhaps should be noted in the write-up of the bridging steps.

User manual snip from page 32 is below:

![image](https://user-images.githubusercontent.com/4992918/35771352-291de4d4-08e0-11e8-82f1-2ae1b6f6efa6.png)
