### ISSUE TITLE
Create a new parameter \Phi to distinguish from the previous \phi?

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#387]
It's a little confusing on page 41. Having \phi represent two things will likely cause confusion in the meeting. 

If we switch then we should edit the SRG report's \Phi to \phi (page 44), to avoid real confusion. 

Might involve a few changes, so thought I'd open for discussion. 

And since the epsilon's in (5) and (7) are not the same thing, I suggest appending a ' to one of them. I thought the one in (5) since only appears once.

**Comment by taylori** [comment]
I already changed the \Phi to \phi in the SRG recommendation (figuring that the difference wasn't intentional).

I've struggled with the old/new meaning of the \phi and indeed it's confusing, so using \Phi would be fine. The epsilon's in (5) and (7) have different meaning in terms of the impact on the model, but in terms of parameters that we report in Table E.1 with names starting with "AgeSel_P3_Fishery.1._DEVadd_1991", they are identical. Nevertheless, since we never connect E.1 to the equations, adding a ' makes sense to separate them, especially if it's consistent with a change in the \phi notation.

Note that \phi also occurs frequently in the sections on bridging and sensitivity analyses among other areas.

I can help with this tomorrow if you wish.

**Comment by taylori** [comment]
Note that I never added this figure (previously posted to https://github.com/cgrandin/hake-assessment/issues/323#issuecomment-361778573)
![logistic_transformation](https://user-images.githubusercontent.com/4992918/36055735-6db665e4-0db3-11e8-9ee1-8e9292774077.png)

The simple code to create it is in https://github.com/cgrandin/hake-assessment/blob/master/doc/r/r-functions/selectivity-transformation-notes.r and could be augmented or captioned to note that the old phi/epsilon was in the vertical dimension, while the new Phi/epsilon' is in the horizontal dimension.

**Comment by andrew-edwards** [comment]
I think we're done with this (I changed a bunch yesterday, making sure to keep \phi when referring to 2017 model). The figure above can be shown if anyone requests more explanation.
