### ISSUE TITLE
Mountains and selectivity plots (27 and 28) imply age 6+ not fully selected for 2010-2012, but are for other years

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#390]
The phrase 'almost fully selected by age-4 in 2010 and 2012..' on p52 confused me a little. Actually, the word 'almost'. Does omitting 'almost' make more sense?

But it still means that 2010-2012 older fish aren't fully selected, whereas they are for other years. Presumably that's okay (and results were similar last year). Maybe just omitting 'almost' will sort it out!

**Comment by cgrandin** [comment]
This makes sense to me, also removing the parentheses would make it better.

**Comment by andrew-edwards** [comment]
Okay - and the older ones don't get fully selected presumably because the fishery is targetting the larger younger cohorts in those years.

**Comment by taylori** [comment]
I agree that the text could be improved. I would maybe say something like 

> The median selectivity peaks at age 4 in 2010 and 2012 and at age 3 in 2011 suggesting targeting of the younger cohorts in those years. This pattern is consistent with the 2008 cohort appearing strong in the fishery age compositions initially, but decreasing in prominence from 2013 onward (Figure 24 [age comp fits] and Figure 58 [squid plot])

Blue line in panel (c) of figure 52 shows example where having peak selectivity at age 3 causes the 6+ fish to be < 100% selected (blue lines are MLE estimate for 1991, an arbitrary year that just happened to illustrate the point well). In the semi-parametric setup in panel (f), the older fish are at 100% and age 3 is  > 100%). The interpretation of fishing mortality changes between these two cases, where the semi-parametric would have a lower fishing mortality rate for that year to compensate for the higher average selectivity. However, since our fishing mortality reference points are all in units of SPR, not F directly, I believe that this differences truly don't matter. The view that it really doesn't matter is supported by this comparison of the relative fishing intensity in the base model and the semi-parametric model
```
SSplotComparisons(SSsummarize(list(base.model, sens.models.4[[2]])), legendlabels=c("Base model", "2018.40.20_semiPara_tvSelect_sig1.0"), subplot=6)
```

![image](https://user-images.githubusercontent.com/4992918/36065066-40aa817e-0e4a-11e8-898c-413c892a8be4.png)

**Comment by andrew-edwards** [comment]
Thanks - feel free to make the changes.

**Comment by taylori** [comment]
Text changes approximately as discussed in commit da7a4eb.
