### ISSUE TITLE
Canadian JV catch was double-counted

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#391]
Due to a very small bug in the catch code, the JV catch was lumped into the Shoreside catch as well as being reported separately. This means the JV catch was added to the Canadian total twice, so the value should be 5608 t less than what we used in the model. I apologize for this, it really was a tiny bug (two characters on one line of code). I think the impact will be minimal, as it's only 1% of the catch but maybe we should run a sensitivity and have it ready for the SRG.

I uploaded the corrected file into the Google drive. It's called
`JVCorrected-Canada-Landings_Fleet_Year_Month.csv`

**Comment by cgrandin** [comment]
This affects all years in which there was a JV fishery since 2007. This is how many tonnes each year's catch is out:


2007 | 6780.39
-- | --
2008 | 3592.281
2010 | 8081.45
2011 | 9716.611
2017 | 5607.515

**Comment by andrew-edwards** [comment]
I was going to say it's somewhat cancelled out by the US catch issue #366, for which Aaron said:
```
I'm being told that the best numbers for now, which are still not rectified in our PacFIN database, are the following:

2016: additional treaty landings of 2522.75 mt
2017: additional treaty landings of 6405.86 mt

These values would then be added to annual totals.
```
However, you're saying that it affects earlier years also. The 2011 one is 3.3% of the total catch.

For a sensitivity we should maybe incorporate Aaron's value as well. Or maybe not, keep the two issues separate.

Or correct everything and get the MCMC's going again. But it seems a bit late for that, and the sensitivites would get confusing unless we re-ran those also (by just changing the catch values in the input files). 

Hmmm.....

**Comment by taylori** [comment]
Good catch finding this, even if timing isn't awesome.
I would vote to not re-run anything at this late stage and just add this to a sensitivity. I think that combining it with the missing tribal catch (which impacts both 2016 and 2017) makes sense. The total impact is likely to be small regardless.

If something more significant comes up in the SRG that convinces us to change the base model, then we could fold this correction into that change, but for now, I don't see it as a big deal and safer to not re-run models.

**Comment by cgrandin** [comment]
Ok, I will run this sensitivity and add it as a new sensitivity case to the document. This will change some figure numbering.

**Comment by cgrandin** [comment]
I'll also change the files `landings-tac-history.csv` and `can-ss-catch-by-month.csv` so that the catch tables are reporting the corrected catch.

**Comment by andrew-edwards** [comment]
Ian - great, that's the answer we were hoping for. 

Chris - why not just use Aaron's updated numbers also, and then just replace his sensitivity with your new ones. Then we don't have an extra sensitivity. 

We can report the corrected catch values in the tables, and have a note somewhere explaining what values of catches were used in the model, but that it doesn't make a big difference based on the sensitivity analysis.

**Comment by taylori** [comment]
Sensitivity models group 2 only has 4 models in it at the moment (compared to 6 models in groups 4 and 6). Plus group 2 includes the "2018.40.19_USageComp" which is related to changes in input data, so I think it would be a good fit to just add it to that group, represented in Figures 47-48.

We would need to add a bullet to the list of sensitivities, and add some text in that section to note what the impact is, but that all should be easy.

We may also want to make a choice about how we display and caption the tables of catch to either note the catch not reflected in the tables, or note what amount of catch in the tables is not reflected in the models.

**Comment by taylori** [comment]
Our two messages there seem to have crossed paths but said the same thing regarding the tables.

**Comment by cgrandin** [comment]
That sounds good, I'll add to sensitivity group 2. Should I make the additional adjustments for the tribal catch as seen in issue #366 as well so it is all in one sensitivity?

**Comment by andrew-edwards** [comment]
Yes Ian. I hadn't realised that Aaron's sensitivity wasn't shown.

**Comment by taylori** [comment]
It might be worth running 3 models for our own purposes: 1. tribal fix, 2. JV fix, and 3. both, but then only adding the both option to the document. That way we would understand the individual impacts but I don't think there's need to clutter the document with more than 1.

**Comment by andrew-edwards** [comment]
Maybe get '3. both' done first as we know we want to show that. Expect JV fix wouldn't show anything that we can't infer from '3 both'.

**Comment by cgrandin** [comment]
That sounds like a good plan. I'll do those three and post them to the models folder on Google drive when done. I'll add the 'both' model into sensitivity group 2.

**Comment by taylori** [comment]
Third paragraph on page 28 includes references to values including `last.year.us.not.attained.tonnes` and `last.year.us.not.attained` and a non-dynamic value for tribal catch of 6,012 t in 2017.

Reading through this makes me think that it would be simpler to leave the tables and these values from custom-knitr-variables.r unchanged, and just note the missing catch in a caption or an additional column in the existing tables. That way the tables, text, and models will all be consistent with each other instead of trying to keep track of the old vs. new numbers and what's where.

**Comment by andrew-edwards** [comment]
I think most of the numbers are automated (but, yes, we'd have to check). I kind of feel it's better to have the catch tables reflect the correct numbers, and the caveat says what the model was run with (but sensitivity implies it doesn't really matter).
Easier than adding new columns to tables, which gets quite fiddly.

**Comment by cgrandin** [comment]
Here are my calculations for the 3 new models.
[Catch-calcs-add-jv-and-tribal-corrections.xlsx](https://github.com/cgrandin/hake-assessment/files/1713675/Catch-calcs-add-jv-and-tribal-corrections.xlsx)

**Comment by taylori** [comment]
Numbers in the Excel file look right to me based on the values reported in the comments.

Andy, that's a good point on keeping things simple. We always have this issue and #366 to refer to if we want to add non-dynamic notes about catch not included in the model. In the commit 353e48d08e7a114a5fe5b3cc956d0a32d1db5913 that I just made to the intro section, I just added this note so we go make sure the text matches the numbers within it.
** [Rewrite paragraph below after finalizing the tables and dynamic numbers]

**Comment by cgrandin** [comment]
The new models are now on Google drive. They are:

```
2018.40.21_corrected_jv_tribal_catch
2018.40.22_corrected_jv_catch
2018.40.23_corrected_tribal_catch
```

**Comment by cgrandin** [comment]
There is a problem with the case we want to use which includes both adjustments, `2018.40.21_corrected_jv_tribal_catch`. The hessian is not positive definite which means the covar.sso file isn't written and the build() fails. It is fine for the other two cases. What should we do about this?

**Comment by taylori** [comment]
Strange. I'll take a look. Definitely supports the decision not to switch over the base model.

**Comment by taylori** [comment]
I haven't figured out why this model would be messing up. The incomplete Report.sso file from the model with the bad Hessian messes up the comparison plots, so I ran it again with -nohess to get a more complete output. This confirms that the differences are tiny (see trivial change in 2018 spawning biomass and plot below). 

However, the lack of uncertainty around the base model would make the plot look a bit different than otherwise, so I'll keep digging into it to see if I can figure out what's going on.

> base.model$derived_quants["SSB_2018","Value"]/h40.21nohess$derived_quants["SSB_2018","Value"]
[1] 1.000041

![image](https://user-images.githubusercontent.com/4992918/36066065-780a9dee-0e58-11e8-8241-f0f5ed07d033.png)

**Comment by andrew-edwards** [comment]
Wouldn't have thought that small changes to catch numbers should mess up the numerics. Thanks for looking into.

**Comment by taylori** [comment]
Found a fix. 

Tiny change like this definitely should not mess things up. I think that ADMB's algorithms sometimes just goes off the rails with so many parameters at play.

I just tried changing the initial value of the SR_LN(R0) parameter and that worked. The model with failed Hessian has been renamed to 2018.40.21_BAD_corrected_jv_tribal_catch and 2018.40.21_corrected_jv_tribal_catch now contains the model with the new starting value. It's a tiny bit more different than the base model, but still less than a 1% change in final biomass.

base.model$derived_quants["SSB_2018","Value"]/h40.21$derived_quants["SSB_2018","Value"]
[1] 1.008173
![image](https://user-images.githubusercontent.com/4992918/36066320-736b2b92-0e5c-11e8-9e75-f5869e726bbd.png)

**Comment by cgrandin** [comment]
Thanks Ian.

I have it as a new sensitivity in commit d2573b8faba16d052f0dba1d50ebc3c93e3fb020.

I changed the catch table (`landings-tac-history.csv`) so that the double-counted JV values have been accounted for. The Shoreside values are now less for 2007, 2008, 2010, 2011, and 2017.

** I didn't add the U.S. tribal catch to the table because I'm not sure which column to add them to. **
So, we should leave this open until that is done.

I'm heading out now, but will check back later.

**Comment by taylori** [comment]
The changes all look good. Thanks @cgrandin.
The unaccounted for U.S. tribal catch is all in the Shoreside sector, so I will make those changes now.

I'll also make an initial edit to the research and data needs based on the thoughts I posted to #381 yesterday, recognizing that further edits can be made by anyone who wishes.

**Comment by andrew-edwards** [comment]
Thanks Ian. I flagged a section in the Introduction section to check that the US paragraph is still good. Please take a look when you've updated the catches.

**Comment by andrew-edwards** [comment]
Fun to see Aaron's face when he checks his notifications, expecting a few minor discussions about edits and hyphenation!

**Comment by aaronmberger** [comment]
Just make sure to use tribal catch values currently in the document, I can’t recall if they are the same as my github post.  The tribal thing has been an ongoing set of adjustments

**Comment by taylori** [comment]
Snipped from Page 31 has the following, indicating small differences from the notes in issue #366.
![image](https://user-images.githubusercontent.com/4992918/36066849-6bd2531a-0e66-11e8-9360-6749b0393b87.png)
1677 instead of 2522.75 for 2016 and
6172 instead of 6405.86 for 2017

However, to make matters even more complex, the [landings-tac-history.csv](https://github.com/cgrandin/hake-assessment/blob/master/data/landings-tac-history.csv) file has a 2016 coastwide total that is 1225.71 higher than the value in the base model (329427, identical to the 2016 base model). I presume that was an effort to account for this same issue, where the total we got at the time was just a bit different than the revised numbers above. We just need to be careful to not double count the correction.

Ultimately, since we're not changing the base model, we just need to accurately account for what the totals are supposed to be and then report the difference. And it also highlights why making ad-hoc fixes instead of getting the original databases fixed can be problematic.

@aaronmberger do you have time to check the U.S. catch numbers for 2016 and 2017 in the CSV file and make them correct? If so, I can take the results of that and re-run the sensitivity analysis if needed?

**Comment by taylori** [comment]
That would be great.
For the U.S. Shoreside catch, here's what I **think** the values should be, but since you are closer to both the data extractions and the conversation about the tribal catch, it would be good if you check:

For 2017, I think it should be the old CSV file value, 144671.6, **plus** 6172 that's reported missing on page 31.
For 2016, I think it should be the old CSV file value 86345.64, **minus** the 1225.71 difference between the 2016 total catch and the 2016/2017 base models, **plus** the 6172 reported missing on page 31.

**Comment by cgrandin** [comment]
Just a note that I put the US tribal additions as I got them from issue #366 into the sensitivity text, hardwired, so if those numbers have changed we need to update that.

**Comment by aaronmberger** [comment]
Okay... I worked through the catch again and the long and short of it is that we should do a sensitivity to one single new catch stream, which is a compilation of three changes.  This new catch stream is based on the following changes (as highlighted in the attached spreadsheet):

1. Tribal catch: there have been two sets of 2016 and 2017 tribal catch values going around, one being the total 2016 and 2017 tribal catch and one being the difference between the total tribal catch and the tribal catch currently in PacFIN (see spreadsheet).  We want to add the later, the missing tribal catch.  So Chris I think the values need to be updated to missing tribal catch =  1,678 (2016) and 6,172 (2017).  My apologies for not specifying these difference better.  The tribal catch issue has been, and continues to be, an issue and I wouldn't say at this point that it is final final. So even if this didn't come to us VERY late in the assessment cycle, it still would probably go into a sensitivity as these changes aren't even in our regional database yet (PacFIN).

2.  Canadian JV: as Chris mentioned there is double counting of JV catch for years going back as far as 2007 and these should be subtracted from our new total.  If we look at the ratio of change between our current base model .dat file and our new (all 1, 2, and 3 of these items included) sensitivity catch stream, the largest change is ~3% drop in catch in 2011.  Mostly, this ratio from 2007-2017 is near 1.0 (or little to no net change, especially recently; see spreadsheet).

3. Small updates in catch from 2007-2016 somehow were not included in our .dat file.  I don't' know how that happened, other than I see multiple versions of the .dat file as I was building it up, and apparently loaded the one that had added 2017 catch but hadn't yet updated pre-2017 (2007-2016) catch.  This is completely a user error on my part, so sorry guys.  This will have a small influence on the total catch stream (base model results) and our bridging model results that adds pre-2017 catch.  The overall addition in catch is very small (see spreadsheet), but nonetheless the base model catch is inaccurate from 2007-2016.

What to do?  Given the small net change to catch from items 1, 2, and 3 above, I suggest that we just add  a single sensitivity to an 'alternative catch stream'.  This alternative catch stream includes two items (2 and 3) that should definitely be done (changes made) either for this year's or next year's base model, and one item (1) that likely needs more investigation to ensure it represents best accounting of total tribal catch (i.e., correct absolute value and no double counting occurring).  I will run the sensitivity and add it to our model directory shortly, but I will be very surprised if it makes any difference.

Thoughts?

[TotalCatch2017.xlsx](https://github.com/cgrandin/hake-assessment/files/1714478/TotalCatch2017.xlsx)

**Comment by taylori** [comment]
Aaron, thanks for digging into this. I like your suggestion for the path forward. If you have time to put the data file together, that would be great, but now that you've figured out what's going on, please feel free to go back to spending time with your family.

I woke up early so am watching Newcastle v Manchester United where former Seattle Sounder DeAndre Yedlin is keeping pace with Alexis Sanchez. But I could be doing something more useful.

**Comment by aaronmberger** [comment]
I've added a model (2018.40.25_alternativeCatch) to our google drive models folder.  Also attached a pdf here summarizing sensitivity plots for this model relative to our base model - can't tell the difference between the two.

[CompareAltCatch.pdf](https://github.com/cgrandin/hake-assessment/files/1714501/CompareAltCatch.pdf)

**Comment by aaronmberger** [comment]
Given the hour, I'm almost thinking we only bring this up and show at SRG.  Just so we don't spend a bunch of time changing things (even text) in case SRG wants something different. Still should change text related to 'missing tribal catch' in the document as mentioned above.

Thoughts?

**Comment by aaronmberger** [comment]
I love Saturday and Sunday morning football... enjoy!

**Comment by taylori** [comment]
Thanks Aaron.  
I'm OK either describing all this in detail or leaving it out of the document, so will leave it to Andy and Chris to make the call. Given that the new sensitivity has already been added, and some text written, I don't think it would be too big a burden to tidy things up. And we'd be obligated to update all the tables for the post-SRG version regardless of whether there's any change to the base model.

If we stay the course that Andy was in favor of yesterday, I think these are the steps that need to happen:
- replace 2014.40.21 with 2014.40.25 in sensitivity group 2
- revise landings-tac-history.csv to reflect the revised numbers where the totals should match the data file catch in 2014.40.25 of 332331 for 2016 and 440945 for 2017.
- revise sensitivity text to describe the change and the very small change in model results
- figure out where best to add any additional text noting the difference and the choice to not update the base model and all sensitivities 1 day prior to the deadline

Alternatively, we could
- remove the new sensitivity from group 2
- restore the csv file to the state it was in on Friday
- remove any text related to this difference
- focus on presenting these differences at the SRG meeting instead of in the main document

**Comment by aaronmberger** [comment]
Right, I had forgotten the 20+ comments above mentioning that you guys already did a bunch of this, so I guess I'm leaning towards option 1 (your first set of bullets)...

Cheers guys, I'll be stepping away for awhile but should have time to check back in later today to see if other unforeseen monkeys have arisen.

**Comment by andrew-edwards** [comment]
Agree - first set of bullets, given it's modifyihng yesterday's runs, and some other stuff. Ian/Chris - are you able to make the changes (Chris might not be working too much today, but it shouldn't be too much work I think). I want to focus on edits, thanks. Bit slow getting going this morning (family sickness rather than watching soccer), but all good, I'm just working at home.

**Comment by taylori** [comment]
If everyone can download the 2014.40.25 model, I will make edits to the csv file and revise text.

I probably won't get to that until later in the day today, but given that no other parts of the document depend on those changes, I don't think there's a rush now that we've agreed on the plan.

**Comment by cgrandin** [comment]
Hi guys, I've been in bed all morning due to my chest cold. If this hasn't been done by tomorrow morning I will make the changes. Ian, if you have other stuff to do go ahead, I can do this.

**Comment by andrew-edwards** [comment]
Take it easy Chris, I think Ian can take care of it.

**Comment by andrew-edwards** [comment]
Put a placeholder *** in Sensitivity Analyses section 3.8, assessment-section.rnw.

**Comment by taylori** [comment]
Sorry to push this back to @aaronmberger, but while trying to update the landings csv file, I realized that I don't actually know whether all of the minor changes listed in the third bullet of [his comment above](https://github.com/cgrandin/hake-assessment/issues/391#issuecomment-364758052) go to the U.S. Shoreside or some to the CP or Mothership sectors.
I could go back to the data extractions, but there's more risk of messing things up that way and I suspect that it would be more efficient for Aaron to just make the changes on Monday.

**Comment by aaronmberger** [comment]
I just updated the .csv total landings file.  I'll I had to do was add the missing tribal catch for 2016 and 2017 as the double counted Canadian JV was already changed in that file.  The minor changes listed in the third bullet are a mute point for the .csv file, because these were already correctly incorporated into that file (those were missing from the base model .dat file)

**Comment by andrew-edwards** [comment]
Thanks Aaron. Yes, the Canadian values already appear in the main tables (and reflect updated total catch last year of  434,773 t. So I think:
1. When I merge your above commit in that number should change slightly.
2. Download the new 2014.40.25 (I haven't done that yet).
3. Update the sensitivity analysis grouping, and add some text (Ian to do, but if not available I can do it).
4. Add a caveat in the Exec Summary? Might just create unnecessary confusion/angst - maybe just explain clearly in the main text, reference the Sens run and say that it's not going to greatly impact the main results and conclusions.

**Comment by taylori** [comment]
Thanks Aaron, I somehow lost the plot in forgetting that the change to the SS data file was to make it match the updated catch estimates which are reflected in the table, so only SS needed to change (as you did in 2014.40.25), not the csv file itself (other than the addition of the tribal catch once we decided to throw that into the mix with this sensitivity).

Andy, yes your list looks right. I've got a 45 minute window to contribute, which should be enough to update model-setup.r to change 2018.40.21_corrected_jv_tribal_catch into 2018.40.25_alternativeCatch and update text around that sensitivity.

I'm OK with or without a caveat in the Exec Summary. I think that can be Andy's call.

**Comment by andrew-edwards** [comment]
See my comment above. Can use that for some of the text.

**Comment by taylori** [comment]
OK, I just committed changes in 6f263ba. Aaron had already added text on the tribal catch issue to the end of the section 2.1.1 Total catch, which seems like a good place to talk about issues related to total catch. Rather than have a bunch of redundant text, I chose to put the detailed description of the 3 issues into this paragraph, and just refer to it in the sensitivity analysis.
@andrew-edwards, if this doesn't feel right to you, feel free to shift the details into the sensitivity instead.

Note: `source('all.r')` is needed to get new `model-setup.r`.

I'll next take a look at the paragraph in Section 1.4.1 Overview of the fisheries in 2017 that starts with
`** [Rewrite paragraph below, if necessary, after finalizing the tables and dynamic numbers]`

**Comment by taylori** [comment]
Section 1.4.1 paragraph looks OK now. Feel free to check it over.
I haven't actually built the doc since these last 2 commits but am out of time, so hopefully I didn't break anything.

**Comment by andrew-edwards** [comment]
Thanks, just rebuilding now (I forgot to do build() which broke it). Will check text - looked good on the GitHub commit page.

**Comment by andrew-edwards** [comment]
Doing some minor edits. Final sentence:
```
Taken together, the net effect of these changes was an average change of 
0.5\% in total catch over the years 2007 to 2017. The total change 
was 15,798 t over a period with total catch of over 300,000,000~t.    [I put millions in numbers to make it easier to compare]
```
Is the 0.5% from working out the change each year then taking the mean of those? 
Isn't it 0.005%?  I get that from doing
```
> 15798/(3e8) * 100
[1] 0.005266
```

**Comment by andrew-edwards** [comment]
Could just give the total change and it's percentage (i.e. take out the average change sentence).

**Comment by taylori** [comment]
I calculated change in each year relative to catch on each year. Since that
both round to the same value, simplification makes sense.

**Comment by andrew-edwards** [comment]
Your 0.5% is correct - I screwed up when I changed your 3million to 300,000,000! Will fix and simplifiy text.
