### ISSUE TITLE
Time varying plots contain log transformation code which should be removed

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#428]
Found while sipping beer and wine at the SRG. The log-transformation should be removed to account for the new big Phi = 7 * small phi

**Comment by taylori** [comment]
The plot was indeed wrong, but I was incorrect about the cause. The transformation already got removed as noted on https://github.com/cgrandin/hake-assessment/issues/323#issuecomment-362401458.
However, I never checked the revised function to confirm that it was now producing correct estimates. It turns out that I was incorrect about how the parameter deviations are applied in SS 3.30. It turns out that now the deviations are all treated as standard normal and what's added to the base value is the product of Phi and the deviations. 

Equation (7) should be revised from
p_ay = p_a + epsilon_ay 
to
p_ay = p_a + Phi*epsilon_ay 
and then I think the Phi^2 should be removed from the denominator in Equation (8), but I want to check that before making the edits to the equations.

Commit d50d42a108ee266649cc82bfc27df1839fb1ed77 fixes the plot in the quickest way possible, with a hack whereby Phi = 1.4 is added to the function. So making this plot for a model with a different Phi value would require additional steps to come out right.

![image](https://user-images.githubusercontent.com/4992918/36718029-2e23b332-1b55-11e8-9a35-226e8744fdc8.png)

**Comment by andrew-edwards** [comment]
Realised it's (probably) okay. Phi not estimated so could be outside summation, but fine as is.
