### ISSUE TITLE
List of editorial-y things (not major text edits) to do before final submission

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#438]
- [x]  Remove 'draft' from:
- [x] from cover title and footnote
- [x] reinsate citation
- [x] footnote
- [x] update acknowledgements
- [x] spell check on .tex
- [x] check dangling headings (at bottom of pages)
- [x] skim through checking figures look okay
- [x] actually read some of it if time (doubtful!)

**Comment by andrew-edwards** [comment]
Am uploading the latest build to SRG drive.

- [ ] I'll compare Chris and my builds
- [ ] I'll take a look at Jaclyn's edits that she gave me
- [ ] We can read over tomorrow as time permits. 
- [ ] I'll post final version to SRG Google Drive and email Stacey and Frank

**Comment by andrew-edwards** [comment]
Version on JTC Drive was Chris’s for me to compare. It was only a few commits behind mine that I only put on SRG drive. FYI

**Comment by andrew-edwards** [comment]
Just uploaded a revised version before leaving the hotel - did a few minor commits this morning. In compare-pdfs, hake-assessment-2Mar-845am.pdf.

Noticed that Chris's .pdf was 3Mb or so larger than mine, but I went through them yesterday and they were identical (except minor edits, and scatterplot figures had slightly different fonts so maybe they just rendered differently). Not an issue. 

Probably offline until ferry or home.... Will try and read at least the exec summary in the car, though flicking through not much has changed. I'll check for any comments/issues before submitting, hopefully when get home around 3:30pm. 

Great job everyone!

**Comment by taylori** [comment]
I just pushed a set of edits to appendix-srg-requests-2018.rnw in commit ac7c4ff.
None of these changes are essential, but I think they make the section look less like it was thrown together quickly during the review panel (which of course it was).

Changes include 
- Revised text at top of section on alternative run 
  - List individual probabilities for current status and 2017 fishing intensity to go with joint probability
  - Expanded text about tables and figures shown in this section (Table refs not yet dynamic links)
- Revised timeseries comparisons of base vs. alt model
  - Plots now dynamic instead of pre-build .eps files (I needed this for JMC talk anyway)
  - Legends now match current model names (but aren't dynamic)
  - Switched plot from rec devs to absolute recruitment
  - Added fishing intensity comparison
- Moved phase plot to almost the end rather than have it as first figure of this section.
- Replaced boxplot of Default HR catch with distribution plot using SSplotComparisons (most important probabilities from old plot now in paragraph at the top of this section)

**Comment by taylori** [comment]
Minor additional revision added in commit 906251f, to include phase plots for both models in Figure A.6. This helps compare the two and also make this sentence at the top of this section accurate: "Figures A.4-A.7 compare results from the alternative run to those of the based model run."

I'm now stepping away to eat lunch. I'm going to focus on the JMC presentation after lunch, but will keep watch on the issues of anything comes up.

**Comment by cgrandin** [comment]
Thanks Ian, that looks much better!
I read through while on the ferry and everything looks ok.
I changed the JV catch percentage in the text, so make sure to merge my changes as well before submission.

**Comment by aaronmberger** [comment]
Agree, that sounds good.  I just merged and will build so I can have a read through the executive summary and the SRG request section while looking at the 'in print' version.

**Comment by andrew-edwards** [comment]
Thanks all - we have wireless on the ferry so I'll fetch and merge. Be nice to submit at 2:30, but it sounds like Aaron may like a bit more time? If so I can do it later. Chris can tell me if anything else is needed, and it sounds like Ian will be busy with JMC presentation.

**Comment by andrew-edwards** [comment]
Just merged - all looks good.

**Comment by taylori** [comment]
Nice that the ferry has wifi.

I haven't actually read through much of the text in a long time, so having Aaron take the time for an additional read through the exec summary and SRG requests seems like a good idea.

Frank just inquired by email about our timeline and asked that we mail him the final version for distribution. Posting to Google Drive would likely work just as well, but perhaps it should go in the main SRG folder or in a new sub-folder, like "post-SRG Documents", rather than in the "presentations" folder which is pretty cluttered at this stage. I told Frank we were trying to get it done by the end of the day today.

**Comment by aaronmberger** [comment]
I looked over the new exec summary and SRG appendix and those seem good to go.   I'm not going to re-read other sections in the main document as I've done it once before and between us and Trevor's edits we should be pretty good -- check here when your ready to submit:

- [ ] Aaron
- [ ] Andy
- [ ] Chris
- [ ] Ian

**Comment by andrew-edwards** [comment]
Great - just about ot get off the ferry. Yes, I'll post to SRG drive and email (already composed).

**Comment by aaronmberger** [comment]
Going back over my SRG notes - the only thing that came to mind was if we want to explicitly add in the research and data needs section research on defining equilibrium conditions and reference points.  Though there already is a general research need for fecundity and maturity and MSE - combined they kind of cover it.  I'm fine either way...

**Comment by taylori** [comment]
Good thinking. Even so, I'm happy to just keep them as they are rather than make further edits at this stage, given that we're aware of the need and the SRG will demand that we explore it regardless. But if someone wants to propose an edit, I'm happy to read it.

**Comment by andrew-edwards** [comment]
Good point, but, yes, can leave as is.....

Submitting....

**Comment by andrew-edwards** [comment]
Done - thanks guys, another great team effort.

**Comment by andrew-edwards** [comment]
![image](https://user-images.githubusercontent.com/6977190/36927246-321ac776-1e31-11e8-8393-e995c60f326d.png)

**Comment by cgrandin** [comment]
Thanks Andy,

Enjoy your weekend guys! It's well deserved!
