### ISSUE TITLE
Document builds for 2018/2019 cycle. Notes on building methods.

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#457]
I have the document building as of commit c20bd7f288a9fdf43c09580fbdde5a89a30a3154. The old bridging analysis appendix from last year (SS version 3.24 -> 3.30) is not included. So this isn't an exact copy of the assessment from last year, but a starting point for this year.

I reorganized the folder structure a little so that is resembles an R package (all R files are now in the R directory). You can use an RStudio project to build it by opening doc/hake-assessment.rnw in RStudio and clicking "Compile PDF" button or you can build by running the doc/buildtex.bat script. To clean everything up, run the doc/freshtex.bat script. To clean the tex files but not the knitted output (keep cache), use the doc/cleantex.bat script.

Also, go ahead and pull and install r4ss at its current commit.

More packages might be necessary.. the `here` package (https://cran.r-project.org/web/packages/here/index.html) and others found at the beginning of  `all.R`.

**Comment by andrew-edwards** [comment]
Good to see everyone. I got it building (on the ferry), had to rerun a few things because of the change in folder structure (and I think because on Tuesday I may have run `build(T, F, F)` but then cancelled it - this deleted some files but didn't recreate them -- Aaron, I hope I didn't tell you to do that also; if you can't get it working then Chris can help ;) 

There are a couple of undefined refs but no need to worry about those yet.
