### ISSUE TITLE
Problem loading wtatage file in base model. Required for cohortCatch() function

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#479]

**Comment by andrew-edwards** [comment]
Turns out that wtatage.ss_new is not always getting built. e.g. 2019.01.01.

It did for 2019.01.15, so rerunning that to check. Yes, builds okay in a new run.

wtatage.ss is identical for 2019.01.01 and 2019.01.15. hake_control.ss differs in a few expected (due to nature of sensititivy runs) places, as does hake_data.ss . 

Try running 2019.01.01 again:

**Comment by andrew-edwards** [comment]
Okay, so 2019.01.15 works but 2019.01.00_base_model does not, despite wtatage.ss files being the same.

Start with 2019.01.15 and incrementally work back to 2019.01.00. 
Do this in 2019.01.99. 

Thought it might be the space needed before the final 999, but no.

And when it doesn't work it doesn't update covar.sso (Chris - that explains the timestamp warnings we were getting).

**Comment by andrew-edwards** [comment]
2019.01.01_h_prior_mean_low did not work, but 2019.01.02_h_fix_high did (as did some others). So compare the files for those runs:

wtatage.ss identical, hake_data.ss identical, hake_control.ss only difference is  INIT, PRIOR [mean] and PHASE for SR_BH_steep, as expected.

Bit worrying that we might therefore be running into computational issues rather than that we've made a simple error.

Okay, copy   2019.01.02_h_fix_high into 2019.01.98_test_from02  and set phase from -4 to 4 (to estimate h using a prior based on the high fixed value). Then increment down towards the base case. 

phase -4 to 4: works (though h may get stuck at 1 numerically, I didn't check)

change INIT from 1.00 to 0.88 (the base case value, so control file then the same; this shouldn't work): doesn't work.

Think it hasn't found maximum. Looking at Report.sso (haven't looked at before) it says:
```
Convergence_Level: 1.58968 is_final_gradient
```
but for 2019.01.02 (that does work) it says:
```
Convergence_Level: 1.78032e-05 is_final_gradient
```

Okay, success. Gradient.dat has (presumably) partial derivatives for each parameter, can tell they are not small for the non-converging one.

Guess we presumed there'd be a clearer error for non-convergence, and didn't check. Lesson learned.

So, starting with a higher initial value for h would seem to sort it out. 

Try INIT = 0.95. That works. 

So I think we should change that in the base case. Double check other files are the same: YES.

Okay, let's go with 2019.02.... to avoid confusion (especially given these notes).

**Comment by andrew-edwards** [comment]
Haven't actually checked all the 2019.01.XX ones that did converge. Hoping that increasing the INIT value works for them all.

**Comment by andrew-edwards** [comment]
*Summary* 

So we originally thought the error was from our fecundity matrix (and how we generated it with the new R function), but hadn't initially realised it was a convergence issue that didn't occur for all runs (they all ran okay before for 2019.00.XX before we included time-varying fecundity).

**Comment by andrew-edwards** [comment]
@cgrandin - I uploaded the new base with short mcmc runs. Not sure why some of the files in mcmc/ still have yesterday's date stamp. Will set up a long mcmc chain before leaving.
Have done all the sensitivities - hopefully can build before I have to go in a few minutes...

**Comment by andrew-edwards** [comment]
build(T, T, T) - Looks like it's redoing lots of mcmc stuff for `last.yr.base.model.dir.name <- "2018.40_base_model"
` 
Won't be able to test tonight... Got the long MCMC running so we can hopefully build on Monday (I'm free in the afternoon now)...

**Comment by cgrandin** [comment]
I've gone over everything. Fixed it so that only the base model has things happening for build(T,T,T).

The wtatage.ss_new file appears to be 0 bytes for mcmc runs and forecasts.

**Comment by cgrandin** [comment]
This looks to be fixed
