### ISSUE TITLE
Fix the data summary table

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#526]
Seems like we need to agree on version of r4ss, and then the command. See various commits for changes and comments (e.g. 289cfac, 523ca37f58, and Issue #520). 

I'll assign to the Americans :)

**Comment by aaronmberger** [comment]
Well, since Kelli is on the stock synthesis design team (where's the/our t-shirts?), I'll leave it up to her.  Just let us know here and then make any needed changes to figures-data.R

**Comment by aaronmberger** [comment]
Sorry, re use of development branch for r4ss or not...

**Comment by kellijohnson** [comment]
**development** branch it is. 
@cgrandin fixed us up with a611e00525cb4ec2ec22a0cb91e5ffb6c91edd6d

**Comment by taylori** [comment]
I just tagged the current state of the `development` branch as `hake2019`, so in the future, you should be able to do
```
devtools::install_github('r4ss/r4ss', ref='hake2019')
```
You might want to add that to one of your scripts (perhaps with a note to considering updating next year) because there are some changes to r4ss that need to happen for other assessments that will hopefully not impact hake, but just in case this would keep you safe.

**Comment by kellijohnson** [comment]
thanks @taylori

**Comment by cgrandin** [comment]
Thanks @taylori, I have made it my routine to install the newest version of the **r4ss** development branch  from GitHub in November, and fix any problems with the hake assessment at that time.
