### ISSUE TITLE
Suggestions/comment regarding sensitivity talk

### ISSUE THREAD

**Issue by andrew-edwards** [cgrandin/hake-assessment#570]
Still to do:
- [x] font sizes #565 
- [x] Summary slide
- [x] copy edit again
- [x] practice what to say (mostly know I think, but should actually go through it)

**Comment by cgrandin** [comment]
Font sizes fixed for heatmap axis tick labels - see ecb3d9af73f7ec5c27434bfd99b4bd33b4fddddd

**Comment by kellijohnson** [comment]
That was a lot of work. Good job Andy. Here are some comments.
- I fixed some typos w/ eb265fe9179c74f53219031ce01ae72a8f1c4331
- I changed the \itemize structure on slide 27 with 91f38c9c2e73697afbc9d2c7ab1a0d7fcfb2d203
- slide 30: It is unclear when "Time-varying fecundity?" is not "Y", how is the model configured? Does it use the mean 1975-2018 for 1975-2018?
- slide 30 ...: I am unsure of what you are going to say when certain rows / columns are red, but you don't always highlight the column header. I thought maybe you only did this when an entire column was red, but you don't. So, your logic isn't quite clear.
 - slide 31-34: I think that in the future it might be good to make these plots with larger labels but not label every year or age. I do not think it is worth worrying about for this presentation. Just something to think about because if people didn't have the document to refer back to then there is no way they can read the years. Sorry this is Andre's voice projecting through because it has not been long enough since defending, so my voice is still dictated by not wanting to aggravate him. I will put it on my todo list for future to make this an option when printing these. 
 - slide 35: can you add a red vertical line or something at year 1975 because my first thought was why in the heck is the yellow line so far below the others in the early years. Duh ..., but it took a while for me to dawn on the fact that this is when fecundity assumptions may differ. 
 - slide 36: I would move this to before slide 35 and do the same for the following slides. So, have the table, then spawning biomass followed by relative spawning biomass, and finally the table before the next set.
 - slide 42 - 45: I am guessing that these always come after sensitivities? In my brain they would be better placed after the MCMC MLE comparison, but feel free to completely ignore this to remain status quo.
 - slide 46: Great plot. @aaronmberger do we do this for the PFMC stocks, if not, I think we should bring it up at a team meeting.

**Comment by aaronmberger** [comment]
The historical  assessment plot hasn't been done for many (if any) PFMC stocks that I'm aware of, partly because there may be 3 three lines for many of them (or 2), others like sablefish it would work nicely.  I do like this retrospective assessments plot.

**Comment by andrew-edwards** [comment]
Thanks guys. Kelli - I'll add notes to your bullet points.....
