### ISSUE TITLE
Fig 49, if want will need .csv file

### ISSUE THREAD

**Issue by aaronmberger** [cgrandin/hake-assessment#76]
Allan, do you have a copy of the "HakeAssessHistory.csv"?  I see it is called in the AssessmentHistoryPlot.R code to make Fig 49.  That is if we even want to include that figure...

**Comment by allan-hicks** [comment]
It is in the data folder. However, you may not be able to get it since our
forks are separate. You would have to merge mine, which I'm not willing to
try out with less than 24 hours left.  Can you wait until tomorrow morning
after Chris merges it all? If not, I can send you the pdf or we can figure
out a way to sync.

**Comment by cgrandin** [comment]
I changed the name of the file and fixed an error in the plot legend, so I think it's finished.
