### ISSUE TITLE
"anticipated opportunity cost of not fishing for alternative species"

### ISSUE THREAD

**Issue by allanhicks** [cgrandin/hake-assessment#89]
What does this mean and where did this information come from? Management performance subsection just before "Model Uncertainty" section

**Comment by aaronmberger** [comment]
feel free to change verbage.... the residual bio-economist in me I
guess.... Low utilization comes from (at least what I heard at JTC
meetings) was 1) not finding aggregations and 2) the decision to go fishing
for other things (the latter is the above economics of fisheries
translation of that; i.e., fishing for other species was preferred because
from an investment standpoint it was anticipated to be a better economical
decision)

On Mon, Feb 8, 2016 at 2:11 PM, allanhicks <notifications@github.com> wrote:

> What does this mean and where did this information come from? Management
> performance subsection just before "Model Uncertainty" section
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrandin/hake-assessment/issues/89>.
>



-- 

*Aaron M. Berger, Ph.D. Research Mathematical Statistician*
*Fishery Resource Analysis and Monitoring Division*
*Northwest Fisheries Science Center*
*2032 SE OSU Dr. Bldg. 955*
*Newport, OR 97365-5275*



*aaron.berger@noaa.gov <aaron.berger@noaa.gov>541.867.0562*

**Comment by allan-hicks** [comment]
I'll leave it up to you if this is to be kept in. But, think about
defending this when an SRG member asks, and industry is listening. I tend
to stick with the facts or something I can quote industry on.  I think that
it was implied at our meeting that some boats chose to fish for other
species (like some Freezer Trawlers in Canada), but the shoreside sector
may disagree with you (or at least I didn't here them specifically say
this).  Or, you may want to expand on that statement to provide more
evidence.
Just my thoughts.

**Comment by aaronmberger** [comment]
I'm happy to throw that part out.  Just leave it as 'due, in part, to difficulties locating aggregations of fish.'

**Comment by allan-hicks** [comment]
how about

"to difficulties locating aggregations of fish and possibly economic
reasons"

That will cover the US as well since they didn't fish much in the fall for
both reasons.

**Comment by aaronmberger** [comment]
done and close
