### ISSUE TITLE
How do you get bars on this plot..

### ISSUE THREAD

**Issue by cgrandin** [cgrandin/hake-assessment#9]
For the 'rainbow age comps' figure in the main figures section with the following caption:
"Base model fit to the observed fishery (top) and acoustic survey (bottom) age composition data....."

I can't figure out how to get bars on it instead of dots.

**Comment by andrew-edwards** [comment]
I think the answer is in  age.fits(), which is called by make.age.comp.fit.plot()      (I was looking into my solution to issue 15).
I think it's because what is used to plot the results, which I've now saved as 

    fishery.estimated.age.comp

in all.r, does not have an "Exp.025" column, and so no uncertainties can be plotted. age.fits() has lines:

    if(uncertainty & !"Exp.025" %in% names(agedbase)){
      cat("setting uncertainty=FALSE because intervals for expected values not found\n")
      uncertainty <- FALSE
    }

I'm thinking the cat() output gets lost in the knitr somewhere, but from then on it doesn't try to plot the error bars because of the uncertainty switch, which, although is TRUE in the call from make.age.comp.fit.plot(), then gets overridden to FALSE.  
But, yes, 2015 assessment plot did have error bars. Looks like they can (will?) be done in the code, they're just not currently included in the output?? 
So question is now where to get the values from. I remember with Awatea we only got MLEs for numbers at age, so I somewhat doubt you can get uncertainties from the MCMCs, because it would end up saving so many results?

**Comment by andrew-edwards** [comment]
And I also need the uncertainties for the Exec-summary Recruitment section. I've flagged it in the text.

**Comment by cgrandin** [comment]
Dine - I had to use the model-partest model instead as it has these values.
